#!/usr/bin/env python3
"""Generate the bank's bottom button bar into bank_main.if, and register it in the interface packs.

WHY A GENERATOR. Same reason as tools/genbanktabs.py: twelve buttons, their icon overlays, their
labels, the pack ids and the order file all have to agree, and that is exactly the shape that
drifts when hand-edited. This follows genbanktabs' rules to the letter - see its docstring for
the pack/order agreement rule and why the block is rewritten rather than appended.

WHAT IT DRAWS

  A single 36px row of twelve OSRS-style buttons across the bottom of the bank window:

    [Swap][Insert]  [Item][Note]  [1][5][10][X][All]  [Search]  [Dep inv][Dep worn]

  The four toggles on the left are the components that were already there - com_99/com_100
  (rearrange mode) and com_94/com_93 (withdraw as) - moved onto the row and restyled. They keep
  their ids, their buttontype=select scripts and their existing [if_button] handlers; only their
  geometry and their sprites change. Their six text labels (com_95..com_98, com_101, com_102)
  are deleted: the icons say the same thing in a twelfth of the width.

  Every button is the same pair of sprites - bankbuttons,0 unlit and bankbuttons,1 lit - with a
  separate non-button graphic component drawn on top carrying the icon. That split is what makes
  the highlight free: the background switches on a client-side varp comparison (buttontype=select
  + script1op1=pushvar + script1=eq) and the icon never moves. The icon components are not
  buttons, so they are skipped by the hit test and do not swallow the click.

  The quantity buttons carry a text label rather than an icon. The X button's label is rewritten
  by the server with if_settext once a custom amount has been entered, so it reads "250" the way
  OSRS does rather than staying "X".

  The Search button is the one button the server never hears about: clientcode 221 plus
  buttontype=normal means the client's handleInterfaceAction intercepts it, opens the search box
  and returns false, so no packet is sent. The filter is a view of an inv the client already has.

SPRITE SHEET. sprites/bankbuttons.png is a 10-tile 36x36 strip built by tools/genbanksprites.py
out of the OSRS cache. Index order is fixed by BG_OFF/BG_ON/ICON_* below.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IF = os.path.join(ROOT, 'scripts/interface_bank/interfaces/bank_main.if')
PACK = os.path.join(ROOT, 'pack/interface.pack')
ORDER = os.path.join(ROOT, 'pack/interface.order')

MARK_A = '// ---- bank bottom bar (generated by tools/genbankbar.py - do not hand edit below) ----'
MARK_B = '// ---- end bank bottom bar ----'

SHEET = 'bankbuttons'
BG_OFF, BG_ON = 0, 1
ICON_SWAP, ICON_INSERT, ICON_ITEM, ICON_NOTE = 2, 3, 4, 5
ICON_SEARCH, ICON_DEPINV, ICON_DEPWORN = 6, 7, 8

ROW_Y, BTN = 288, 36
X0, PITCH = 38, 36

# The four existing toggles, in the order they sit on the row. Each is (component, slot index).
# com_99 = Swap, com_100 = Insert, com_94 = Item, com_93 = Note - see bank.rs2's [if_button]s.
TOGGLES = [('com_99', 0, ICON_SWAP, 'swap'),
           ('com_100', 1, ICON_INSERT, 'insert'),
           ('com_94', 2, ICON_ITEM, 'item'),
           ('com_93', 3, ICON_NOTE, 'note')]

# The six text labels the icons replace.
DEAD = ['com_95', 'com_96', 'com_97', 'com_98', 'com_101', 'com_102']

QTY = [('bankqty1', 4, 0, '1', 'Withdraw 1 at a time'),
       ('bankqty5', 5, 1, '5', 'Withdraw 5 at a time'),
       ('bankqty10', 6, 2, '10', 'Withdraw 10 at a time'),
       ('bankqtyx', 7, 3, 'X', 'Withdraw a custom amount'),
       ('bankqtyall', 8, 4, 'All', 'Withdraw everything')]

SEARCH_CLIENTCODE = 221


def slot_x(i):
    return X0 + i * PITCH


def toggle_block(com, i):
    """The replacement body for one of the four existing toggle buttons, ids untouched."""
    return [f'[{com}]',
            'type=graphic',
            f'x={slot_x(i)}',
            f'y={ROW_Y}',
            'buttontype=select',
            f'width={BTN}',
            f'height={BTN}']


def blocks():
    out = [MARK_A, '']
    # icon overlays for the four toggles that already exist above
    for com, i, icon, name in TOGGLES:
        out += [f'[bankicon_{name}]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                f'width={BTN}',
                f'height={BTN}',
                f'graphic={SHEET},{icon}',
                '']
    # quantity buttons
    for name, i, value, label, option in QTY:
        out += [f'[{name}]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                'buttontype=select',
                f'width={BTN}',
                f'height={BTN}',
                'script1op1=pushvar,bankquantity',
                f'script1=eq,{value}',
                f'graphic={SHEET},{BG_OFF}',
                f'activegraphic={SHEET},{BG_ON}',
                f'option={option}',
                '']
    # the three action buttons
    for name, i, icon, option, clientcode in [
            ('banksearch', 9, ICON_SEARCH, 'Search', SEARCH_CLIENTCODE),
            ('bankdepinv', 10, ICON_DEPINV, 'Deposit inventory', None),
            ('bankdepworn', 11, ICON_DEPWORN, 'Deposit worn items', None)]:
        out += [f'[{name}]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                'buttontype=normal',
                f'width={BTN}',
                f'height={BTN}',
                f'graphic={SHEET},{BG_OFF}',
                f'activegraphic={SHEET},{BG_ON}']
        if clientcode is not None:
            out += [f'clientcode={clientcode}']
        out += [f'option={option}', '']
        out += [f'[{name}icon]',
                'type=graphic',
                f'x={slot_x(i)}',
                f'y={ROW_Y}',
                f'width={BTN}',
                f'height={BTN}',
                f'graphic={SHEET},{icon}',
                '']
    # quantity labels last, so they sit on top of their buttons
    for name, i, value, label, option in QTY:
        out += [f'[{name}text]',
                'type=text',
                f'x={slot_x(i)}',
                f'y={ROW_Y + 11}',
                f'width={BTN}',
                'height=14',
                'center=yes',
                'font=p11_full',
                'shadowed=yes',
                f'text={label}',
                'colour=0xFF981F',
                '']
    out += [MARK_B, '']
    return '\n'.join(out)


def main():
    src = open(IF, encoding='utf-8', newline='').read()
    crlf = '\r\n' in src
    body = src.replace('\r\n', '\n')

    body = re.sub(re.escape(MARK_A) + r'.*?' + re.escape(MARK_B) + r'\n?', '', body, flags=re.S)

    # restyle the four toggles in place - keep everything below their geometry (the select scripts)
    for com, i, icon, name in TOGGLES:
        m = re.search(r'\[' + com + r'\]\n(?:[a-z0-9_]+=[^\n]*\n)+', body)
        if not m:
            sys.exit(f'{com} does not look the way this generator expects - refusing to guess')
        keep = [l for l in m.group(0).strip().split('\n')[1:]
                if l.split('=', 1)[0] in ('script1op1', 'script1')]
        if len(keep) != 2:
            sys.exit(f'{com} has lost its select script - refusing to guess')
        block = toggle_block(com, i) + keep + [f'graphic={SHEET},{BG_OFF}',
                                              f'activegraphic={SHEET},{BG_ON}']
        body = body[:m.start()] + '\n'.join(block) + '\n' + body[m.end():]

    # drop the six text labels the icons replace
    for com in DEAD:
        m = re.search(r'\[' + com + r'\]\n(?:[a-z0-9_]+=[^\n]*\n)+\n?', body)
        if m:
            body = body[:m.start()] + body[m.end():]

    body = body.rstrip('\n') + '\n\n' + blocks()
    open(IF, 'w', encoding='utf-8', newline='').write(body.replace('\n', '\r\n') if crlf else body)

    names = re.findall(r'^\[([A-Za-z0-9_]+)\]$', blocks(), re.M)

    # ---- repack. Ids for this block are reused where they already exist (genbanktabs' rule:
    # only one generator can own the tail of interface.pack, and that one is genmenus).
    pack = [l for l in open(PACK, encoding='utf-8', newline='').read().replace('\r\n', '\n').split('\n') if l]
    order_raw = open(ORDER, encoding='utf-8', newline='').read()
    order_crlf = '\r\n' in order_raw
    order = [l for l in order_raw.replace('\r\n', '\n').split('\n') if l]

    mine = {f'bank_main:{n}' for n in names}
    dead = {f'bank_main:{n}' for n in DEAD}
    existing, keep_pack, dropped = {}, [], set()
    for l in pack:
        i, n = l.split('=', 1)
        if n in mine:
            existing[n.split(':', 1)[1]] = i
            dropped.add(i)
            continue
        if n in dead:
            dropped.add(i)
            continue
        keep_pack.append(l)
    order = [l for l in order if l not in dropped]

    used = {int(l.split('=', 1)[0]) for l in keep_pack}
    nxt = max(used) + 1
    for n in names:
        if n in existing and int(existing[n]) not in used:
            i = existing[n]
        else:
            while nxt in used:
                nxt += 1
            i = str(nxt); nxt += 1
        used.add(int(i))
        keep_pack.append(f'{i}=bank_main:{n}')
        order.append(i)
    keep_pack.sort(key=lambda l: int(l.split('=', 1)[0]))
    order.sort(key=int)

    ids = [l.split('=', 1)[0] for l in keep_pack]
    assert len(ids) == len(set(ids)), 'duplicate interface id'
    nm = [l.split('=', 1)[1] for l in keep_pack]
    assert len(nm) == len(set(nm)), 'duplicate interface name'
    assert set(order) == set(ids), 'interface.order and interface.pack disagree'

    open(PACK, 'w', encoding='utf-8', newline='').write('\n'.join(keep_pack) + '\n')
    open(ORDER, 'w', encoding='utf-8', newline='').write(
        ('\r\n' if order_crlf else '\n').join(order) + ('\r\n' if order_crlf else '\n'))
    got = sorted(int(l.split('=', 1)[0]) for l in keep_pack
                 if l.split('=', 1)[1] in mine)
    print(f'{len(names)} components, ids {got[0]}..{got[-1]}; '
          f'row y={ROW_Y}, x {slot_x(0)}..{slot_x(11) + BTN}; dropped {len(DEAD)} labels')


main()
