#!/usr/bin/env python3
"""Write everything the boss kill counts need, from tools/bosskillspec.json.

WHY A GENERATOR. Twelve bosses x five places each - a varp, an index, a name, an increment, a read,
and a row in a window - is seventy-odd entries that all have to agree about which boss is which. A
single one out of step is a counter that counts the wrong monster, and nothing errors.

THE ENGINE CANNOT PICK A VARP AT RUNTIME. engine.rs2 has no varp commands and no enum outputs one,
so there is no %vars[$i]. The increment and the read are therefore GENERATED switch_int procs over
twelve cases each, and the two things that CAN be tables are tables: npc -> index and index -> name.

    python3 tools/genbosskills.py            # write the five files and take pack ids
    python3 tools/genbosskills.py --check     # exit 1 if any of them would change
"""
import json, os, re, sys

C = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(C, 'tools', 'bosskillspec.json')
IFACE = 'boss_kills'
OUT_VARP = os.path.join(C, 'scripts/bosses/configs/boss_kills.varp')
OUT_CONST = os.path.join(C, 'scripts/bosses/configs/boss_kills.constant')
OUT_ENUM = os.path.join(C, 'scripts/bosses/configs/boss_kills.enum')
OUT_IF = os.path.join(C, 'scripts/bosses/interfaces/boss_kills.if')
OUT_RS2 = os.path.join(C, 'scripts/bosses/scripts/boss_kills.rs2')
QUESTLIST = os.path.join(C, 'scripts/interfaces/questlist.if')
VARPPACK = os.path.join(C, 'pack/varp.pack')
IFPACK = os.path.join(C, 'pack/interface.pack')
IFORDER = os.path.join(C, 'pack/interface.order')

# The window. Same framing every other panel in this repo uses: tradebacking tiles at 88x60 across
# a 488-wide area starting at 12,20, and a buttontype=close text at the bottom.
PANEL_X, PANEL_Y, PANEL_W = 12, 20, 488
TILE_W, TILE_H = 88, 60
ROW_H = 16
NAME_X, COUNT_X = 40, 300
FIRST_ROW_Y = 64
COL_TITLE = '0xFF981F'
COL_NAME = '0xFFFFFF'
COL_COUNT = '0xFFFF00'
# The row appended to the quest list, and where it goes in that layer.
QL_ROW = 'boss_kills'
QL_LAYER = 'com_0'


def read(p):
    return open(p, newline='').read().replace('\r\n', '\n')


def build_varp(spec):
    L = ['// ONE PERM VARP PER BOSS. GENERATED - do not hand-edit.',
         '//   python3 tools/genbosskills.py',
         '//',
         '// Twelve separate varps rather than bits in one, because a kill count has no ceiling a',
         '// bit range could hold - four bits stop at fifteen - and a varp is a full int.',
         '//',
         '// NOT TRANSMITTED. The window is filled by if_settext when it opens, so the client never',
         '// needs the numbers; nothing reads them client-side and nothing draws from them.',
         '//',
         '// protect=no IS WHAT MAKES THIS WORK AT ALL, and it cost four builds to find. Varps are',
         '// PROTECTED by default, and writing a protected varp needs the p_active_player pointer -',
         '// which an npc-context death does not have, whatever npc_findhero returns. The build',
         '// failed with "Attempt to access corrupted pointer" at the call site in npc_death.rs2,',
         '// and moving the guard, inlining the switch and dropping the queue all changed nothing',
         '// because none of them was the cause. skill_guide.varp explains the same rule for',
         '// [if_button] triggers, and %barrows_killed_monster - the closest thing in the tree, and',
         '// the template for this whole round - is a varbit on a base varp that carries it.',
         '']
    for b in spec['bosses']:
        L.append('// %s (%s, level %d)' % (b['name'], b['npc'], b['vislevel']))
        L.append('[boss_kc_%s]' % b['key'])
        L.append('scope=perm')
        L.append('protect=no')
        L.append('')
    return '\n'.join(L)


def build_const(spec):
    return '\n'.join([
      '// GENERATED by tools/genbosskills.py - do not hand-edit.',
      '//',
      '// How many bosses keep a count. Everything that loops over them reads this rather than',
      '// twelve, so the thirteenth boss is a line in tools/bosskillspec.json and a regenerate.',
      '^boss_kills_count = %d' % len(spec['bosses']),
      '^boss_kills_none = -1',
      '',
    ])


def build_enum(spec):
    B = spec['bosses']
    L = ['// WHICH BOSS, AND WHAT IT IS CALLED. GENERATED - do not hand-edit.',
         '//   python3 tools/genbosskills.py',
         '//',
         '// These two are tables because they CAN be: an npc maps to an int and an int maps to a',
         '// string, and enum() does both. The increment and the read cannot be tables, because',
         '// this engine has no way to pick a varp at runtime - those are generated switches in',
         '// boss_kills.rs2, and this comment is the reason they look different.',
         '',
         '[boss_kill_index]',
         '// the dying npc -> its slot, or ^boss_kills_none for everything else in the game',
         'inputtype=npc',
         'outputtype=int',
         'default=-1']
    for i, b in enumerate(B):
        L.append('val=%s,%d' % (b['npc'], i))
    L += ['',
          '[boss_kill_name]',
          "// slot -> the name off the boss's own npc record, so the window cannot disagree with",
          '// what the player sees over its head',
          'inputtype=int',
          'outputtype=string',
          'default=null']
    for i, b in enumerate(B):
        L.append('val=%d,%s' % (i, b['name']))
    L.append('')
    return '\n'.join(L)


def build_if(spec):
    B = spec['bosses']
    out, names = [], []

    def com(nm, **kv):
        names.append(nm)
        out.append('[%s]' % nm)
        for k, v in kv.items():
            out.append('%s=%s' % (k, v))
        out.append('')

    out += ['// THE BOSS KILL WINDOW. GENERATED - do not hand-edit.',
            '//   python3 tools/genbosskills.py',
            '//',
            '// Opened from the quest list, which gains one row for it. The counts are pushed in',
            '// with if_settext when it opens rather than transmitted, so the varps stay',
            '// server-side and there is nothing to keep in sync.',
            '']
    # background, the same tiling every panel here uses
    rows = len(B)
    height = FIRST_ROW_Y + rows * ROW_H + 40
    x = PANEL_X
    n = 0
    while x < PANEL_X + PANEL_W:
        w = min(TILE_W, PANEL_X + PANEL_W - x)
        y = PANEL_Y
        while y < PANEL_Y + height:
            com('frame%d' % n, type='graphic', x=x, y=y, width=w,
                height=min(TILE_H, PANEL_Y + height - y), graphic='tradebacking,0')
            n += 1
            y += TILE_H
        x += TILE_W
    com('title', type='text', x=PANEL_X, y=PANEL_Y + 8, width=PANEL_W, height=14,
        font='b12_full', shadowed='yes', center='yes', colour=COL_TITLE, text='Boss kill counts')
    com('subtitle', type='text', x=PANEL_X, y=PANEL_Y + 26, width=PANEL_W, height=14,
        font='p12_full', shadowed='yes', center='yes', colour=COL_NAME,
        text='Every boss you have felled.')
    for i, b in enumerate(B):
        y = PANEL_Y + FIRST_ROW_Y + i * ROW_H
        com('name%d' % i, type='text', x=NAME_X, y=y, width=240, height=14,
            font='p12_full', shadowed='yes', colour=COL_NAME, text=b['name'])
        # The count text starts at 0 rather than blank: an empty row reads as a broken window, and
        # a player with no kills should see twelve zeroes rather than twelve gaps.
        com('count%d' % i, type='text', x=COUNT_X, y=y, width=120, height=14,
            font='p12_full', shadowed='yes', colour=COL_COUNT, text='0')
    com('close', type='text', x=PANEL_X, y=PANEL_Y + height - 24, width=PANEL_W, height=14,
        font='p12_full', shadowed='yes', center='yes', buttontype='close',
        colour=COL_NAME, overcolour=COL_COUNT, text='Close Window', option='Close')
    return '\n'.join(out), names


def build_rs2(spec):
    B = spec['bosses']
    L = ['// THE BOSS KILL COUNTS. GENERATED - do not hand-edit.',
         '//   python3 tools/genbosskills.py',
         '//',
         '// ~boss_kill_record is called from [proc,npc_death], which is the one funnel every death',
         '// in the game passes through - and the only one available, because a second [ai_queue3]',
         '// on an npc that already has one is a hard build error and eight of these twelve already',
         '// have theirs for a drop table. ~barrows_potential hangs off the same place for the same',
         '// reason, and is the template for the whole shape of this file.',
         '//',
         '// CREDIT IS npc_findhero, the test every drop table in this tree opens with, so a kill',
         '// counts for exactly the player the loot went to. %npc_aggressive_player is the LAST',
         '// attacker and is a different thing. Slayer deliberately SPLITS a task kill when those',
         '// two differ; a kill count is not split, because two players each being told they killed',
         '// the same boss is a wrong number rather than a generous one.',
         '//',
         '// THE MESSAGE IS QUEUED because mes() wants a player context an npc-context death does',
         '// not have. The COUNTER is not queued: protect=no on the varps is what lets it be',
         '// written from here, and boss_kills.varp says why at length. Four builds were spent',
         '// moving this guard, inlining a switch and dropping a queue before the varp',
         '// declaration turned out to be the answer - the same answer %barrows_killed_monster',
         '// has had the whole time, on a base varp that carries protect=no.',
         '//',
         '// THE GUARD IS THE FIRST THING IN THE PROC, and it is about CREDIT rather than about',
         '// the pointer. Without it the counter would be written for whoever the death context',
         '// happened to be pointing at. It went missing for one build while the pointer error was',
         '// being chased, and the build went GREEN with it gone - which is the whole reason the',
         '// battery checks for it by name.',
         '[proc,boss_kill_record]',
         'if (npc_findhero = ^false) {',
         '    return;',
         '}',
         'def_int $slot = enum(npc, int, boss_kill_index, npc_type);',
         'if ($slot = ^boss_kills_none) {',
         '    return;',
         '}',
         '// TWELVE CASES IN THE OPEN. This is what "the engine cannot pick a varp at runtime"',
         '// costs, and there is no way to spend less: no %vars[$i], no enum that outputs a varp.',
         '// A default case, so a slot outside the table does nothing rather than incrementing the',
         "         // first boss's counter.",
         'switch_int ($slot) {']
    for i, b in enumerate(B):
        L.append('    case %d : %%boss_kc_%s = add(%%boss_kc_%s, 1);' % (i, b['key'], b['key']))
    L += ['    case default : return;',
          '}',
          'queue(boss_kill_announce, 0, $slot);',
          '',
          '// THE MESSAGE IS QUEUED, because mes() wants a player context an npc-context death does',
          '// not have. The queue re-reads the count rather than being handed it, so the number the',
          '// player is told is the number that is stored.',
          '[queue,boss_kill_announce](int $slot)',
          'mes("Your <enum(int, string, boss_kill_name, $slot)> kill count is: '
          '<tostring(~boss_kill_get($slot))>.");',
          '',
          '// THE READ-BACK SWITCH. This is the other half of what "no runtime varp index" costs:',
          '// twelve cases to read one counter. A default of 0, so a slot outside the table reads',
          "// as no kills rather than as the first boss's.",
          '[proc,boss_kill_get](int $slot)(int)',
          'switch_int ($slot) {']
    for i, b in enumerate(B):
        L.append('    case %d : return(%%boss_kc_%s);' % (i, b['key']))
    L += ['    case default : return(0);',
          '}',
          '',
          '// THE WINDOW. Opened from the row this generator appends to questlist.if, which is the',
          '// same idiom every quest row already uses to open its journal.',
          '[if_button,questlist:%s] ~boss_kills_open;' % QL_ROW,
          '',
          '[proc,boss_kills_open]',
          'if_openmain(%s);' % IFACE]
    for i in range(len(B)):
        # if_settext is (component, string) - the other way round is a build error, which is
        # how the first version of this generator found out.
        L.append('if_settext(%s:count%d, tostring(~boss_kill_get(%d)));' % (IFACE, i, i))
    L.append('')
    return '\n'.join(L)


def patch_questlist(spec, check):
    """Append one row to the quest list's scrolling layer, and grow its scroll to fit.

    IT DOES NOT OWN THE FILE. Only its own block and the layer's scroll= line are touched, the
    same way tools/genxplock.py inserts into stats.if - so the 129 quest rows already there are
    left exactly as they are.
    """
    txt = read(QUESTLIST)
    block = '\n'.join([
      '',
      '// APPENDED by tools/genbosskills.py - do not hand-edit. Opens the boss kill window; the',
      '// trigger is [if_button,questlist:%s] in bosses/scripts/boss_kills.rs2.' % QL_ROW,
      '[%s]' % QL_ROW,
      'layer=%s' % QL_LAYER,
      'type=text',
      'x=10',
      'y=%d',            # filled in below
      'buttontype=normal',
      'width=131',
      'height=14',
      'font=p12_full',
      'shadowed=yes',
      'text=Boss kill counts',
      'colour=0xFF981F',
      'overcolour=0xFFFFFF',
      'option=View boss kill counts',
      '',
    ])
    # WHERE IT GOES: under the last row in the layer, found by reading the y= of every child of
    # that layer rather than by counting quests.
    ys = []
    cur = None
    inlayer = False
    for line in txt.split('\n'):
        t = line.split('//')[0].strip()
        m = re.match(r'^\[(\w+)\]$', t)
        if m:
            cur, inlayer = m.group(1), False
            continue
        if t == 'layer=%s' % QL_LAYER:
            inlayer = True
        elif inlayer and t.startswith('y=') and cur != QL_ROW:
            ys.append(int(t[2:]))
    if not ys:
        raise SystemExit('genbosskills: found no children of %s in questlist.if' % QL_LAYER)
    row_y = max(ys) + 22
    block = block.replace('y=%d', 'y=%d' % row_y)

    # IDEMPOTENCE, and it took two runs to get right. The first version of this removal wanted a
    # blank line after the block - and the block is the LAST thing in the file, so there is none.
    # The second run appended a duplicate and the packer said so: "Layer questlist:com_0 already
    # has boss_kills as a child". genxplock.py hit the same fault on stats.if. So: from the
    # marker comment to the next block header at column 0, or to the end of the file.
    old = re.search(r'(?ms)\n*// APPENDED by tools/genbosskills\.py.*?\n\[%s\]\n'
                    r'(?:(?!\n\[).)*(?=\n\[|\Z)' % re.escape(QL_ROW), txt)
    if old:
        txt = txt[:old.start()] + txt[old.end():]
    txt = txt.rstrip('\n') + '\n' + block
    # and the layer has to be tall enough to scroll to it
    want_scroll = row_y + 30
    def fix(m):
        return 'scroll=%d' % max(int(m.group(1)), want_scroll)
    head, sep, rest = txt.partition('\n\n')
    head = re.sub(r'scroll=(\d+)', fix, head, count=1)
    txt = head + sep + rest
    if not check:
        open(QUESTLIST, 'w', newline='').write(txt)
    return txt, row_y


def take(path, names, check, crlf=False):
    """Give every name an id in a tracked pack file, keeping the ones it already has."""
    txt = read(path)
    have = {n: int(i) for i, n in re.findall(r'^(\d+)=(\S+)$', txt, re.M)}
    used = set(have.values())
    nxt = (max(used) + 1) if used else 0
    added = []
    for n in names:
        if n in have:
            continue
        while nxt in used:
            nxt += 1
        have[n] = nxt
        used.add(nxt)
        added.append('%d=%s' % (nxt, n))
    lines = ['%d=%s' % (i, n) for n, i in sorted(have.items(), key=lambda kv: kv[1])]
    if not check and added:
        open(path, 'w', newline='').write('\n'.join(lines) + '\n')
    return have, added


def take_order(path, ids, check):
    txt = read(path)
    cur = [int(x) for x in txt.split('\n') if x.strip().isdigit()]
    want = sorted(set(cur) | set(ids))
    if not check and want != cur:
        open(path, 'w', newline='').write('\n'.join(str(i) for i in want) + '\n')
    return want != cur


def main():
    check = '--check' in sys.argv
    spec = json.load(open(SPEC))
    iftext, ifnames = build_if(spec)
    want = {OUT_VARP: build_varp(spec), OUT_CONST: build_const(spec),
            OUT_ENUM: build_enum(spec), OUT_IF: iftext, OUT_RS2: build_rs2(spec)}
    qtext, row_y = patch_questlist(spec, check)
    want[QUESTLIST] = qtext

    varps = ['boss_kc_%s' % b['key'] for b in spec['bosses']]
    ifall = [IFACE] + ['%s:%s' % (IFACE, n) for n in ifnames]

    if check:
        bad = []
        for path, body in want.items():
            have = read(path) if os.path.exists(path) else None
            if have != body:
                bad.append(os.path.relpath(path, C))
        _, a1 = take(VARPPACK, varps, True)
        _, a2 = take(IFPACK, ifall + ['questlist:%s' % QL_ROW], True)
        if a1:
            bad.append('varp.pack is missing %s' % ', '.join(a1))
        if a2:
            bad.append('interface.pack is missing %s' % ', '.join(a2))
        if bad:
            print('genbosskills --check: ' + '; '.join(bad))
            return 1
        print('genbosskills --check: every generated file and both pack files are already what '
              'this writes')
        return 0

    for path, body in want.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, 'w', newline='').write(body)
        print('wrote %s' % os.path.relpath(path, C))
    _, a1 = take(VARPPACK, varps, False)
    ids, a2 = take(IFPACK, ifall + ['questlist:%s' % QL_ROW], False)
    take_order(IFORDER, [ids[n] for n in ifall + ['questlist:%s' % QL_ROW]], False)
    print('%d bosses, %d components, quest row at y=%d, %d varp ids, %d interface ids'
          % (len(spec['bosses']), len(ifnames), row_y, len(a1), len(a2)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
