#!/usr/bin/env python3
"""Write the clan chat tab (clanchat.if) and the Clan Setup window (clan_setup.if).

    python tools/genclanchat.py

THE TAB is tab 7, the one 377 left empty and 2008 gave to clan chat. It is drawn in the frame of 474's
Friends tab (474 interface 550: the steel border, the orange title, two stone buttons under a list),
so it sits beside Friends and Ignore as one of a set. Its contents are the CLIENT's - like the friends
list, every changing part is a client code the client fills from the UPDATE_CLANCHANNEL packet
(Client.updateClanContent in Client-Java):

    1001 "Talking in: ..."   1002 "Owner: ..."   1003 Join Chat / Leave Chat (the button and its label)
    1005 the list's scroll layer   1101-1200 member names (Kick)   1201-1300 member worlds

so this file only has to put them in place. Join/Leave and Kick never reach the server as button
clicks; the client sends CLAN_JOINCHAT / CLAN_KICK itself. Clan Setup is an ordinary button, handled in
clan_chat/scripts/clan_chat.rs2.

THE WINDOW is Clan Setup: the channel's name and who may enter, talk and kick. Its values are set by
script (~clan_setup_refresh) from the engine's clan_name / clan_rank.

The 474 border art is i474_*.png in sprites/, brought over by LostCityServer's
tools/models/port474if.py from 474 interface 550.

After writing, pack/interface.pack and .order are brought into line with tools/ifids.py.
"""
import os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'scripts', 'clan_chat', 'interfaces')

ORANGE = '0xFF9933'
MAX_MEMBERS = 100
ROW = 15

# 474 interface 550's frame, as port474if.py converts it: corners, then the tiled edges (the last
# tile of the top and bottom edges is a cropped copy, because 377 cannot clip a graphic to its box)
FRAME = [(3, 20, 25, 30, 'i474_310'), (146, 20, 25, 30, 'i474_311'), (3, 194, 25, 30, 'i474_312'),
         (146, 194, 25, 30, 'i474_313'),
         (28, 5, 36, 36, 'i474_314'), (64, 5, 36, 36, 'i474_314'), (100, 5, 36, 36, 'i474_314'),
         (136, 5, 11, 36, 'i474_314_11x36'),
         (150, 50, 36, 36, 'i474_315'), (150, 86, 36, 36, 'i474_315'), (150, 122, 36, 36, 'i474_315'),
         (150, 158, 36, 36, 'i474_315'),
         (-12, 50, 36, 36, 'i474_172'), (-12, 86, 36, 36, 'i474_172'), (-12, 122, 36, 36, 'i474_172'),
         (-12, 158, 36, 36, 'i474_172'),
         (28, 203, 36, 36, 'i474_173'), (64, 203, 36, 36, 'i474_173'), (100, 203, 36, 36, 'i474_173'),
         (136, 203, 10, 36, 'i474_173_10x36')]


class If:
    def __init__(self, head):
        self.lines = list(head)

    def com(self, name, **kv):
        self.lines.append('')
        self.lines.append('[%s]' % name)
        for k, v in kv.items():
            self.lines.append('%s=%s' % (k.rstrip('_'), v))

    def write(self, name):
        os.makedirs(OUT, exist_ok=True)
        with open(os.path.join(OUT, name + '.if'), 'w', encoding='utf-8', newline='\r\n') as f:
            f.write('\n'.join(self.lines) + '\n')


def tab():
    f = If(['// GENERATED by tools/genclanchat.py - do not hand edit.',
            '// Drawn by the client (Client.updateClanContent); Clan Setup is clan_chat/scripts/clan_chat.rs2.',
            'type=overlay'])
    for i, (x, y, w, h, g) in enumerate(FRAME):
        f.com('frame%d' % i, type='graphic', x=x, y=y, width=w, height=h, graphic='%s,0' % g)
    f.com('title', type='text', x=4, y=4, width=180, height=14, center='yes', font='b12_full',
          shadowed='yes', text='Clan Chat', colour=ORANGE)
    f.com('talking', type='text', x=10, y=24, clientcode=1001, width=160, height=14, font='p12_full',
          shadowed='yes', text='Talking in: Not in chat', colour=ORANGE)
    f.com('owner', type='text', x=10, y=38, clientcode=1002, width=160, height=14, font='p12_full',
          shadowed='yes', text='Owner: None', colour=ORANGE)
    f.com('list', type='layer', x=8, y=56, clientcode=1005, width=158, height=162, scroll=163)
    for i in range(MAX_MEMBERS):
        f.com('name%d' % i, layer='list', type='text', x=4, y=2 + i * ROW, buttontype='normal',
              clientcode=1101 + i, width=96, height=14, font='p12_full', shadowed='yes',
              colour='0xFFFFFF', option='Kick')
        f.com('world%d' % i, layer='list', type='text', x=100, y=2 + i * ROW, clientcode=1201 + i,
              width=56, height=14, font='p12_full', shadowed='yes', colour='0xFFFFFF')
    # the two buttons and their labels, where 550 has Add Friend and Del Friend
    f.com('join', type='graphic', x=15, y=224, buttontype='normal', clientcode=1003, width=72,
          height=36, graphic='i474_293,0', option='Join Chat')
    f.com('setup', type='graphic', x=95, y=224, buttontype='normal', width=72, height=36,
          graphic='i474_293,0', option='Clan Setup')
    f.com('join_label', type='text', x=21, y=236, clientcode=1003, width=61, height=13, center='yes',
          font='p11_full', shadowed='yes', text='Join Chat', colour=ORANGE)
    f.com('setup_label', type='text', x=101, y=236, width=60, height=13, center='yes',
          font='p11_full', shadowed='yes', text='Clan Setup', colour=ORANGE)
    f.write('clanchat')


# the window: a tradebacking panel with a steel border, the way xprate_choose.if draws its own
PANEL_X, PANEL_Y, PANEL_W, PANEL_H = 116, 64, 280, 196
TILE_W, TILE_H = 88, 60
ROWS = [('name', 'Clan name:', 'Set name'), ('enter', 'Who can enter chat:', 'Change'),
        ('talk', 'Who can talk on chat:', 'Change'), ('kick', 'Who can kick on chat:', 'Change')]


def window():
    f = If(['// GENERATED by tools/genclanchat.py - do not hand edit.',
            '// Scripts: clan_chat/scripts/clan_chat.rs2 (values come from clan_name / clan_rank).'])
    n = 0
    for y in range(PANEL_Y, PANEL_Y + PANEL_H, TILE_H):
        for x in range(PANEL_X, PANEL_X + PANEL_W, TILE_W):
            f.com('frame%d' % n, type='graphic', x=x, y=y, width=min(TILE_W, PANEL_X + PANEL_W - x),
                  height=min(TILE_H, PANEL_Y + PANEL_H - y), graphic='tradebacking,0')
            n += 1
    for i, (x, y) in enumerate(((PANEL_X, PANEL_Y), (PANEL_X + PANEL_W - 25, PANEL_Y),
                                (PANEL_X, PANEL_Y + PANEL_H - 30),
                                (PANEL_X + PANEL_W - 25, PANEL_Y + PANEL_H - 30))):
        f.com('corner%d' % i, type='graphic', x=x, y=y, width=25, height=30, graphic='steelborder,%d' % i)
    for i, x in enumerate(range(PANEL_X + 25, PANEL_X + PANEL_W - 24, 36)):
        f.com('top%d' % i, type='graphic', x=x, y=PANEL_Y - 15, width=36, height=36, graphic='steelborder2,0')
        f.com('bottom%d' % i, type='graphic', x=x, y=PANEL_Y + PANEL_H - 21, width=36, height=36,
              graphic='miscgraphics,3')
    for i, y in enumerate(range(PANEL_Y + 29, PANEL_Y + PANEL_H - 30, 36)):
        f.com('left%d' % i, type='graphic', x=PANEL_X - 15, y=y, width=36, height=36, graphic='miscgraphics,2')
        f.com('right%d' % i, type='graphic', x=PANEL_X + PANEL_W - 21, y=y, width=36, height=36,
              graphic='steelborder2,1')

    f.com('title', type='text', x=PANEL_X, y=PANEL_Y + 10, width=PANEL_W, height=14, center='yes',
          font='b12_full', shadowed='yes', text='Clan Setup', colour=ORANGE)
    f.com('close', type='text', x=PANEL_X + PANEL_W - 92, y=PANEL_Y + 10, buttontype='close', width=68,
          height=11, font='p11_full', shadowed='yes', text='Close Window', colour='0xC00000',
          overcolour='0xFFFFFF')
    for i, (key, label, verb) in enumerate(ROWS):
        y = PANEL_Y + 36 + i * 30
        f.com('%s_label' % key, type='text', x=PANEL_X + 20, y=y + 7, width=130, height=14,
              font='p12_full', shadowed='yes', text=label, colour=ORANGE)
        f.com(key, type='rect', x=PANEL_X + 150, y=y, buttontype='normal', width=110, height=26,
              fill='yes', colour='0x3E3529', overcolour='0x5A4D3B', option=verb)
        f.com('%s_value' % key, type='text', x=PANEL_X + 150, y=y + 7, width=110, height=14,
              center='yes', font='p12_full', shadowed='yes', text='', colour='0xFFFFFF')
    f.com('hint', type='text', x=PANEL_X, y=PANEL_Y + PANEL_H - 30, width=PANEL_W, height=14,
          center='yes', font='p11_full', shadowed='yes',
          text='Set no name to close the channel.', colour='0xC8C8C8')
    f.write('clan_setup')


def main():
    tab()
    window()
    subprocess.check_call([sys.executable, os.path.join(ROOT, 'tools', 'ifids.py'), 'clanchat', 'clan_setup'])


main()
