#!/usr/bin/env python3
"""Which monsters already reach the shared rare table - derived, not hand-listed.

The drop-rate boost grants extra draws on ~ultrarare_getitem, and it is GATED on monsters whose own
table already routes into that proc. Without the gate a boosted player could pull a dragon med helm
off a goblin, which is a new drop SOURCE rather than a rate boost - and it would read worst in
realism, the mode that is meant to be the authentic one. With it, a boosted kill can only ever
produce a drop that monster could already have produced; its rare slot simply comes up more often.

The membership is read out of the scripts themselves:

  1. every .rs2 whose code (comments stripped) calls ~ultrarare_getitem
  2. every [ai_queue3,X] trigger in those files
  3. a trigger on _<category> expands to every npc carrying category=<category>

so a drop table written later that routes into the shared rare slot is covered the next time this
runs, and one that does not cannot quietly acquire the boost. gamemode_battery.py re-derives the
same set on every run and fails if the checked-in enum has drifted from it.

    python3 tools/gendroprate.py
"""
import os, re, sys

C = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = 'scripts/gamemodes/configs/droprate.enum'
PROC = '~ultrarare_getitem'

def code(path):
    raw = open(path, newline='').read().replace('\r\n', '\n')
    return '\n'.join(l.split('//')[0] for l in raw.split('\n'))

# scripts/gamemodes/ is skipped, and the reason is not tidiness: droprate.rs2 CALLS
# ~ultrarare_getitem, so without this it counts itself as a drop table. It carries no [ai_queue3]
# so it adds no monsters, but it moved the script count in the header and the enum stopped being
# byte-identical to its own regeneration - which the battery caught, because that is what the
# re-run check is for.
SKIP = 'scripts' + os.sep + 'gamemodes' + os.sep

def walk(ext):
    for root, _, files in os.walk(os.path.join(C, 'scripts')):
        for f in sorted(files):
            p = os.path.join(root, f)
            if f.endswith(ext) and SKIP not in os.path.relpath(p, C) + os.sep:
                yield p

def derive():
    triggers, files = set(), []
    for p in walk('.rs2'):
        c = code(p)
        if PROC not in c:
            continue
        files.append(os.path.relpath(p, C).replace('\\', '/'))
        triggers |= set(re.findall(r'^\[ai_queue3,(\w+)\]', c, re.M))
    cats = {t[1:] for t in triggers if t.startswith('_')}
    npcs = {t for t in triggers if not t.startswith('_')}
    bycat = {}
    for p in walk('.npc'):
        cur = None
        for line in code(p).split('\n'):
            m = re.match(r'^\[([^\]]+)\]$', line.strip())
            if m:
                cur = m.group(1); continue
            m = re.match(r'^category=(\w+)$', line.strip())
            if m and cur:
                bycat.setdefault(m.group(1), set()).add(cur)
    expanded = {}
    for cat in sorted(cats):
        members = bycat.get(cat, set())
        if not members:
            raise SystemExit('gendroprate: [ai_queue3,_%s] but no npc carries category=%s' % (cat, cat))
        expanded[cat] = sorted(members)
        npcs |= members
    return sorted(files), sorted(npcs), expanded

HEAD = """// Monsters whose own drop table already reaches the shared rare table, and therefore the ones a
// drop-rate boost may grant an extra draw on.
//
// GENERATED by tools/gendroprate.py - {n} npcs out of the {f} scripts that call ~ultrarare_getitem.
// Do not edit by hand; gamemode_battery re-derives this set every run and fails if it has drifted.
//
// THE MISS IS THE ANSWER HERE, which is the one place the usual enum trap works in our favour. An
// enum with no default= returns 0 on a miss, and 0 is exactly what "this monster has no shared rare
// slot" should be - so this table deliberately carries no default= and lists only the monsters that
// do. Every other membership table in this repo wants default=null; this one wants the 0.
//
// {cats}

[droprate_shared_rare]
inputtype=npc
outputtype=int
"""

def main():
    files, npcs, expanded = derive()
    cats = ' / '.join('_%s expands to %s' % (c, ', '.join(m)) for c, m in sorted(expanded.items())) \
        or 'no category triggers among them'
    lines = HEAD.format(n=len(npcs), f=len(files), cats=cats).split('\n')
    lines += ['val=%s,1' % n for n in npcs]
    body = '\n'.join(lines) + '\n'
    path = os.path.join(C, OUT)
    old = open(path, newline='').read() if os.path.exists(path) else None
    open(path, 'w', newline='').write(body)
    print('%d npcs from %d scripts -> %s%s' % (len(npcs), len(files), OUT,
          '' if old == body else '   (changed)'))

if __name__ == '__main__':
    main()
