#!/usr/bin/env python3
"""Generate the elemental weakness table: every npc in this build whose name OSRS gives a weakness.

    python3 tools/genelementalweakness.py            # write the enum
    python3 tools/genelementalweakness.py --check    # exit 1 if it is out of date

WHAT. OSRS (Project Rebalance, May 2024) gives monsters an elemental weakness: for every percent of
it, a strike, bolt, blast or wave of that element gets 1% more accuracy and 1% of its base max hit on
top (oldschool.runescape.wiki/w/Elemental_weakness). The per-monster figures are the wiki's, saved in
tools/elementalweakness.json; this matches them to this build's npcs by their name= and writes

    scripts/skill_combat/configs/magic/elemental_weakness.enum   npc -> element * 1000 + percent

with element 1 air, 2 water, 3 earth, 4 fire (0 is "none", the enum's default). The combat side is
~elemental_weakness_pct in skill_combat/scripts/player/elemental_weakness.rs2.
"""
import json
import os
import re
import sys

C = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SNAP = os.path.join(C, 'tools', 'elementalweakness.json')
OUT = os.path.join(C, 'scripts', 'skill_combat', 'configs', 'magic', 'elemental_weakness.enum')
ELEMENT = {'air': 1, 'water': 2, 'earth': 3, 'fire': 4}


def npcs():
    """(debugname, display name) for every npc config in the tree."""
    out = []
    for root, _, files in os.walk(os.path.join(C, 'scripts')):
        for f in files:
            if not f.endswith('.npc'):
                continue
            cur = None
            for line in open(os.path.join(root, f), encoding='utf-8', errors='replace').read().splitlines():
                m = re.match(r'^\[([A-Za-z0-9_+]+)\]\s*$', line)
                if m:
                    cur = m.group(1)
                elif cur and line.startswith('name='):
                    out.append((cur, line[5:].strip()))
                    cur = None
    return out


def build():
    snap = json.load(open(SNAP))['monsters']
    by = {n.lower(): v for n, v in snap.items()}
    rows = []
    for debug, name in sorted(npcs()):
        w = by.get(name.lower())
        if w:
            rows.append((debug, name, ELEMENT[w['element']] * 1000 + int(w['percent'])))
    lines = ['// GENERATED by tools/genelementalweakness.py from tools/elementalweakness.json - do not hand edit.',
             '// npc -> element * 1000 + percent (1 air, 2 water, 3 earth, 4 fire). OSRS\'s, matched by name.',
             '[elemental_weakness]', 'inputtype=npc', 'outputtype=int', 'default=0']
    lines += ['val=%s,%d' % (d, v) for d, _, v in rows]
    return '\r\n'.join(lines) + '\r\n', rows


def main():
    text, rows = build()
    if '--check' in sys.argv:
        cur = open(OUT, newline='').read() if os.path.exists(OUT) else ''
        # Compared by content, not bytes. This writes CRLF, and git (text=auto) checks the file out
        # with whatever line endings the machine uses - LF on the Linux server - so a byte compare
        # called an up-to-date table stale everywhere but Windows.
        if cur.replace('\r\n', '\n') != text.replace('\r\n', '\n'):
            print('elemental_weakness.enum is out of date - run tools/genelementalweakness.py')
            return 1
        print('elemental_weakness.enum up to date: %d npcs' % len(rows))
        return 0
    open(OUT, 'w', newline='').write(text)
    names = sorted({n for _, n, _ in rows})
    print('%d npcs across %d names' % (len(rows), len(names)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
