#!/usr/bin/env python3
"""Generate the recoloured slayer helmets from tools/slayerhelmspec.json.

Writes three files:

  configs/slayer_helm_colours.obj    one obj per colour per imbue state
  configs/slayer_helm.param          the three params the inheritance doors read
  scripts/slayer_helm_colours.rs2    the recolour, and Check/Disassemble for every colour

WHY A GENERATOR for four items. Because it is not four: the black helmet arrives with the King
Black Dragon in batch 3, and OSRS has eight colours after that, each in a plain and an imbued form.
Configs that differ from each other in two lines are the shape that drifts, and the two lines here
are a recolour pair that has to match the model's own colours exactly or the helmet comes out
black with a coloured smear.

MEMBERSHIP IS THREE PARAMS. slayer_headgear is anything that gives the on-task melee bonus - both
masks and every helmet. slayer_helmet is the four protections a helmet inherits from its parts, so
helmets only: a bare mask has no earmuffs in it. slayer_imbued is the ranged and magic boost. The
three procs that read them are then fixed-size no matter how many colours exist, which is the whole
point - the alternative was a list of item names in three places, growing by two every time a boss
gets a head.

    python3 tools/genslayerhelm.py
"""
import os, io, json, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, 'tools', 'slayerhelmspec.json')
OUT_OBJ = 'scripts/skill_slayer/configs/slayer_helm_colours.obj'
OUT_PARAM = 'scripts/skill_slayer/configs/slayer_helm.param'
OUT_RS2 = 'scripts/skill_slayer/scripts/slayer_helm_colours.rs2'
BASE = 'slayer_helm'


def read(p):
    return io.open(os.path.join(ROOT, p), newline='').read().replace('\r\n', '\n')


def crlf(p):
    raw = open(os.path.join(ROOT, p), 'rb').read()
    return raw.count(b'\r\n') > raw.count(b'\n') / 2


def write(p, lines):
    path = os.path.join(ROOT, p)
    nl = '\r\n' if (os.path.exists(path) and crlf(p)) else '\n'
    open(path, 'wb').write((nl.join(lines).rstrip('\r\n') + nl).encode('utf-8'))


def block(text, name):
    m = re.search(r'^\[%s\]\n(.*?)(?=\n\[|\Z)' % re.escape(name), text, re.S | re.M)
    return m.group(1).split('\n') if m else None


def main():
    spec = json.loads(read('tools/slayerhelmspec.json'))
    src = spec['source']
    base = block(read('scripts/general/configs/osrs_items.obj'), BASE)
    basei = block(read('scripts/general/configs/osrs_items.obj'), BASE + '_i')
    if base is None or basei is None:
        raise SystemExit('genslayerhelm: %s / %s_i are not in osrs_items.obj' % (BASE, BASE))
    objpack = {l.split('=', 1)[1].strip() for l in read('pack/obj.pack').split('\n') if '=' in l}
    err = []
    for c in spec['colours']:
        if c['head'] not in objpack:
            err.append('%s needs %s, which is not in pack/obj.pack' % (c['key'], c['head']))
    if err:
        raise SystemExit('\n'.join('  ERROR ' + e for e in err))

    # ------------------------------------------------------------------ the params
    write(OUT_PARAM, [
        '// What a piece of slayer headgear IS, read by the three procs that decide what it gives.',
        '//',
        '// GENERATED by tools/genslayerhelm.py - do not hand-edit.',
        '//',
        '// The alternative was a list of item names inside ~black_mask_on_task, ~slayer_helm_worn',
        '// and ~black_mask_imbued_on_task, growing by two entries every time a boss gets a head.',
        '// A category would have been simpler again, but an obj gets exactly one and these are',
        '// already armour_helmet, which the Entrana monk and the desert heat both read.',
        '',
        '// Both masks and every helmet: the on-task 7/6 melee bonus.',
        '[slayer_headgear]',
        'type=boolean',
        'default=no',
        '',
        '// Helmets only. A bare black mask has no earmuffs, nose peg or facemask in it.',
        '[slayer_helmet]',
        'type=boolean',
        'default=no',
        '',
        '// The imbued pair and their recolours: 15% to ranged and magic accuracy and damage.',
        '[slayer_imbued]',
        'type=boolean',
        'default=no',
    ])

    # ------------------------------------------------------------------ the objs
    o = ['// The recoloured slayer helmets.',
         '//',
         '// GENERATED by tools/genslayerhelm.py from tools/slayerhelmspec.json - do not hand-edit.',
         '//',
         '// Every one is the plain helmet with TWO RECOLOUR PAIRS and a different name. The helmet\'s',
         '// face mask is the same two colours the black mask itself is made of - rgb15 %d and %d -' % (src['dark'], src['light']),
         '// so the recolour lands on exactly the part OSRS recolours and no new model is needed.',
         '//',
         '// Everything else - the models, the wear positions, the camera, the defences, the Check and',
         '// Disassemble ops - is copied from the plain helmet and its imbued twin, so a colour cannot',
         '// quietly have different stats from the helmet it is a recolour of.',
         '']
    made = []
    for c in spec['colours']:
        for imbued in (False, True):
            key = '%s_%s%s' % (BASE, c['key'], '_i' if imbued else '')
            label = '%s slayer helmet%s' % (c['label'], ' (i)' if imbued else '')
            made.append((key, c, imbued))
            o += ['[%s]' % key]
            for line in (basei if imbued else base):
                line = line.strip()
                if not line or line.startswith('//'):
                    continue
                # The plain helmet declares its own slayer_* params now, and this block adds the
                # right ones below - copying them too gave every colour each param TWICE, which
                # the battery caught. Skip them here; they are decided per variant, not inherited.
                if line.startswith('param=slayer_'):
                    continue
                if line.startswith('name='):
                    o.append('name=%s' % label)
                elif line.startswith('desc='):
                    o.append('desc=%s%s' % (line[5:], '' if imbued else ''))
                else:
                    o.append(line)
            o += ['recol1s=%d' % src['dark'], 'recol1d=%d' % c['dark'],
                  'recol2s=%d' % src['light'], 'recol2d=%d' % c['light'],
                  'param=slayer_headgear,yes', 'param=slayer_helmet,yes']
            if imbued:
                o.append('param=slayer_imbued,yes')
            o.append('')
    write(OUT_OBJ, o)

    # ------------------------------------------------------------------ the script
    r = ['// Recolouring a slayer helmet, and what every colour keeps.',
         '//',
         '// GENERATED by tools/genslayerhelm.py from tools/slayerhelmspec.json - do not hand-edit.',
         '//',
         '// OSRS: buy the unlock with Slayer reward points, then use the head on the helmet. The head',
         '// is consumed. Each colour has its own unlock and its own head, and both are checked - an',
         '// unlock without a head does nothing, and a head without the unlock says why.',
         '//',
         '// THE IMBUE SURVIVES THE RECOLOUR IN BOTH DIRECTIONS. An imbued helmet recoloured stays',
         '// imbued, which is what the paired _i variants are for. Nothing here can turn an imbued',
         '// helmet into a plain one, because the player paid for it.',
         '']
    for c in spec['colours']:
        # ONE TRIGGER, ON THE HEAD. [opheldu,X] normalises which way round the click came and runs
        # the first half that carries a trigger, so a second one on the helmet is not a fallback -
        # it is a duplicate, and a duplicate trigger is a hard build error. The first draft emitted
        # three per colour and rs2check's rule 2 said so.
        r += ['// ---- %s: %s, unlocked with %s' % (c['label'].lower(), c['head_label'], c['unlock']),
              '[opheldu,%s] @slayer_recolour_%s;' % (c['head'], c['key']),
              '',
              '[label,slayer_recolour_%s]' % c['key'],
              'if (~slayer_helm_recolour_pair(%s) = false) {' % c['head'],
              '    ~displaymessage(^dm_default);',
              '    return;',
              '}',
              'if (~slayer_has_unlock(%d) = false) {' % c['bit'],
              '    mes("You need the %s unlock from a Slayer master to do that.");' % c['unlock'],
              '    return;',
              '}',
              'def_namedobj $into = %s_%s;' % (BASE, c['key']),
              'if (inv_total(inv, %s_i) > 0) {' % BASE,
              '    $into = %s_%s_i;' % (BASE, c['key']),
              '}',
              'inv_del(inv, %s, 1);' % c['head'],
              'if (inv_total(inv, %s_i) > 0) {' % BASE,
              '    inv_del(inv, %s_i, 1);' % BASE,
              '} else {',
              '    inv_del(inv, %s, 1);' % BASE,
              '}',
              'inv_add(inv, $into, 1);',
              '~objbox($into, "You fix the %s onto your slayer helmet.", 250, 0, 0);' % c['head_label'].lower(),
              '']
    r += ['// The two halves of the use, either way round: a head and a helmet of some kind.',
          '[proc,slayer_helm_recolour_pair](namedobj $head)(boolean)',
          'if (inv_total(inv, $head) < 1) {',
          '    return(false);',
          '}',
          'if (inv_total(inv, %s) > 0 | inv_total(inv, %s_i) > 0) {' % (BASE, BASE),
          '    return(true);',
          '}',
          'return(false);',
          '']
    r += ['// Check and Disassemble, for every colour. Disassembling a coloured helmet gives back the',
          '// plain parts and the head it was fixed with - the head is not destroyed by taking it off,',
          '// which matches what disassembly already does for the five parts.', '']
    for key, c, imbued in made:
        r.append('[opheld3,%s] @slayer_helm_check;' % key)
    r.append('')
    for key, c, imbued in made:
        r.append('[opheld4,%s] @slayer_helm_split_coloured(%s, %s);'
                 % (key, 'black_mask_i' if imbued else 'black_mask', c['head']))
    r += ['',
          '[label,slayer_helm_split_coloured](namedobj $mask, namedobj $head)',
          'if (inv_freespace(inv) < 5) {',
          '    mes("You need five free inventory spaces to disassemble your slayer helmet.");',
          '    return;',
          '}',
          'inv_delslot(inv, last_slot);',
          'inv_add(inv, $mask, 1);',
          'inv_add(inv, slayer_earmuffs, 1);',
          'inv_add(inv, slayer_facemask, 1);',
          'inv_add(inv, slayer_nosepeg, 1);',
          'inv_add(inv, wallbeast_spike_helmet, 1);',
          'inv_add(inv, $head, 1);',
          'mes("You disassemble your slayer helmet.");',
          '']
    write(OUT_RS2, r)

    print('%s: %d helmets' % (OUT_OBJ, len(made)))
    for key, c, imbued in made:
        print('   %-26s %s recol %d->%d / %d->%d%s'
              % (key, c['key'], src['dark'], c['dark'], src['light'], c['light'],
                 '  imbued' if imbued else ''))
    print('%s: 3 params' % OUT_PARAM)
    print('%s: %d colours, unlock bits %s'
          % (OUT_RS2, len(spec['colours']), [c['bit'] for c in spec['colours']]))
    return made


if __name__ == '__main__':
    main()
