#!/usr/bin/env python3
"""Generate the magic-tablet layer: the objs, their pack ids, the lookup tables and the
scripts that make and break them.

WHY GENERATED. Fourteen tablets times five places each one has to be mentioned - the obj
config, obj.pack, the name/level/needs tables the lectern window reads, the break trigger
and the lectern lists - is seventy entries that all have to agree. One table writes them.

WHERE THE NUMBERS COME FROM. Not from here. A tablet's Magic level, its runes and the
experience making it pays are read out of magic_spell_table at generate time, the same row
the spell itself is cast from, and the battery reads them back. So the Varrock tablet cannot
cost something a Varrock teleport does not, and if the spell row is ever retuned the tablet
follows it on the next run.

WHAT THE WIKI SAYS AND WHAT THIS DOES
  - making a tablet needs the spell's Magic level, its runes, and a soft clay, and pays the
    spell's own experience (35 for a Varrock tablet, which is what the spell pays too)
  - a staff does NOT substitute for a rune at a lectern - you are not casting - so this
    reads runesrequired straight off the row rather than through ~staff_runes
  - breaking a tablet needs NO Magic level and gives NO experience
  - the quest gates stay: an Ardougne tablet still wants Plague City, a Watchtower one still
    wants Watch Tower. Those are on USE, which is where the wiki puts them; making is free.
"""

import os, re, json, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, 'tools/tabletspec.json')
NL = chr(10)
MAX = 8                # rows in poh_tabletmenu, and the stride of ~poh_tab_nth's switch key
NEED_PX = 200          # the needs column in poh_tabletmenu, p11_full
NAME_PX = 126          # the name column, p12_full

def read(p, newline=''):
    return open(os.path.join(ROOT, p), newline=newline).read().replace('\r\n', '\n')

def crlf(p):
    raw = open(os.path.join(ROOT, p), 'rb').read()
    return raw.count(b'\r\n') > raw.count(b'\n') / 2

def write(p, lines, like='scripts/skill_construction/scripts/poh_build.rs2'):
    nl = '\r\n' if crlf(like) else '\n'
    body = nl.join(lines).rstrip('\r\n') + nl
    open(os.path.join(ROOT, p), 'wb').write(body.encode('utf-8'))

def q(s):
    return '"%s"' % s.replace('"', "'")

# --------------------------------------------------------------------------- the spell rows

def spell_ids():
    out = {}
    for m in re.finditer(r'^\^(\w+)\s*=\s*(\d+)\s*$',
                         read('scripts/skill_combat/configs/magic/spells.constant'), re.M):
        out[m.group(1)] = int(m.group(2))
    return out

def spell_rows():
    """{spell constant name: {level, runes[(obj,n)], xp, tele, members}} out of the dbrow file."""
    out = {}
    for b in read('scripts/skill_magic/configs/magic_spells.dbrow').split('\n['):
        m = re.search(r'data=spell,\^(\w+)', b)
        if not m:
            continue
        d = {}
        for l in b.split('\n'):
            if l.startswith('data='):
                k, v = l[5:].split(',', 1)
                d.setdefault(k, []).append(v)
        runes = []
        if 'runesrequired' in d:
            p = d['runesrequired'][0].split(',')
            for i in range(0, len(p) - 1, 2):
                if p[i] != 'null':
                    runes.append((p[i], int(p[i + 1])))
        out[m.group(1)] = dict(level=int(d['levelrequired'][0]), runes=runes,
                               xp=int(d.get('experience', ['0'])[0]),
                               tele=(d.get('tele_coord') or [None])[0],
                               members=(d.get('members') or ['false'])[0] == 'true')
    return out

def obj_costs():
    out = {}
    for b in read('scripts/_unpack/377/all.obj').split('\n['):
        n = b.split(']')[0]
        m = re.search(r'^cost=(\d+)', b, re.M)
        if m:
            out[n] = int(m.group(1))
    return out

# --------------------------------------------------------------------------- fonts

def widths():
    sys.path.insert(0, os.path.join(ROOT, 'tools'))
    import ifrender
    return ifrender.font('p12_full'), ifrender.font('p11_full')

# --------------------------------------------------------------------------- the objs

OBJ_HEAD = '''// The fourteen magic tablets the lecterns make.
//
// GENERATED by tools/gentablets.py from tools/tabletspec.json. Edit the generator.
//
// These are OSRS's own tablets - objs 8007-8020 of the rev 240 cache - imported by
// tools/models/importosrs.py with their models re-encoded into the 317-family format and
// round-trip verified. Name, description, weight and 2d camera are the cache's; so is
// stackable=yes, which is the whole reason a tablet is worth carrying a dozen of.
//
// The first version of this file recoloured obj_zarosstonetablet instead, because nothing in the
// 377 cache is a teleport tablet - Construction arrived after this revision. The real art was one
// cache away and looks like what a player expects, so the recolours are gone.
//
// iop1=Break is on the ones that do something by themselves; the five enchant tablets have no
// iop1 because an enchant needs a target - you use them on the ring or amulet.
'''

def emit_objs(spec, rows, costs, ids):
    o = OBJ_HEAD.split('\n')
    for t in spec['tablets']:
        r = rows[t['spell']]
        cost = sum(costs.get(n, 0) * c for n, c in r['runes']) + costs.get('softclay', 0)
        o += ['[%s]' % t['obj'],
              'name=%s' % t['name'],
              'desc=%s' % t['desc'],
              'model=%s' % t['model']]
        for k in ('2dzoom', '2dxan', '2dyan', '2dzan', '2dxof', '2dyof'):
            if k in t['icon']:
                o.append('%s=%s' % (k, t['icon'][k]))
        if t['kind'] != 'enchant':
            o.append('iop1=Break')
        # stackable is the round's point: fourteen kinds of tablet in one inventory slot each.
        o += ['members=yes', 'stackable=yes', 'weight=%s' % t['weight'], 'cost=%d' % cost, '']
    write('scripts/skill_construction/configs/poh_tablets.obj', o,
          like='scripts/skill_construction/configs/construction.obj')
    return o

def emit_objpack(spec):
    """obj.pack is id=name, one per line, ids dense from 0. Re-running must reuse the ids it
    already handed out rather than append a second block, so drop ours first."""
    p = os.path.join(ROOT, 'pack/obj.pack')
    rows = [l for l in open(p, 'rb').read().decode('utf-8').split('\n') if l.strip()]
    mine = {t['obj'] for t in spec['tablets']}
    keep = [(int(i), n) for i, n in (l.split('=', 1) for l in rows) if n not in mine]
    nxt = max(i for i, _ in keep) + 1
    out = dict(keep)
    for t in spec['tablets']:
        out[nxt] = t['obj']
        nxt += 1
    body = '\n'.join('%d=%s' % (i, out[i]) for i in sorted(out)) + '\n'
    open(p, 'wb').write(body.encode('utf-8'))
    return {n: i for i, n in out.items() if n in mine}

# --------------------------------------------------------------------------- the tables

def need_text(spec, runes):
    words = spec['rune_words']
    parts = ['%d %s' % (c, words[n]) for n, c in runes]
    return ', '.join(parts + ['1 soft clay'])

ENUM_HEAD = '''// What the lectern window shows, and what the tablet scripts look up.
//
// GENERATED by tools/gentablets.py. Edit the generator.
//
// poh_tab_level and poh_tab_need are COPIES of magic_spell_table - the window has to draw a level
// and a shopping list without running a db_find per row per frame - and battery check 40 reads both
// back out of the spell rows and fails if they have drifted. Nothing else here is a copy of
// anything: the make and break scripts ask the db directly.
'''

def emit_enum(spec, rows, ids):
    tabs = spec['tablets']
    o = ENUM_HEAD.split('\n')

    def table(name, outtype, vals, why):
        out = ['// ' + l if l else '//' for l in why.split('\n')]
        out += ['[%s]' % name, 'inputtype=int', 'outputtype=%s' % outtype]
        out += ['val=%s,%s' % kv for kv in vals]
        return out + ['']

    o += table('poh_tab_obj', 'namedobj', [(n + 1, t['obj']) for n, t in enumerate(tabs)],
               'Which obj each tablet is. namedobj and not obj: inv_add takes a namedobj, and an enum\ntyped obj will not pass to it ("Type mismatch: inv,obj,int was given but inv,namedobj,int\nwas expected"). namedobj passes everywhere obj does - if_setobject takes it fine - so this\nis the type that works in both places. The window draws it with if_setobject, which works\nthe icon camera out from the obj config, so there is no zoom table here.')
    o += table('poh_tab_name', 'string',
               [(n + 1, t.get('label', t['name'])) for n, t in enumerate(tabs)],
               'The name as the WINDOW writes it, which is the obj\'s own name unless that name is wider\n'
               'than the 126px column: \'Enchant sapphire or opal\' is 140px, so those two carry a shorter\n'
               'label in the spec. Everywhere else - the inventory, chat - the obj name is the OSRS one.')
    o += table('poh_tab_spell', 'int', [(n + 1, '^' + t['spell']) for n, t in enumerate(tabs)],
               'The spell each tablet stores. Everything else about it - level, runes, experience,\ndestination - is read from that row at runtime.')
    o += table('poh_tab_level', 'int', [(n + 1, rows[t['spell']]['level']) for n, t in enumerate(tabs)],
               'The Magic level to MAKE one. Breaking one needs no level at all.')
    o += table('poh_tab_need', 'string',
               [(n + 1, need_text(spec, rows[t['spell']]['runes'])) for n, t in enumerate(tabs)],
               'The shopping list, in the window\'s own words. Measured against the 176px column by the\ngenerator, which refuses to emit one that overflows.')
    o += table('poh_lectern_name', 'string', [(l['tier'], l['name']) for l in spec['lecterns']],
               'The seven lecterns by their real names. The window\'s subtitle is 488px wide, so unlike\nthe furniture row labels these do not have to be shortened.')
    write('scripts/skill_construction/configs/poh_tablets.enum', o,
          like='scripts/skill_construction/configs/poh_rooms.enum')

# --------------------------------------------------------------------------- the scripts

RS2_HEAD = '''// Making and breaking magic tablets.
//
// GENERATED by tools/gentablets.py from tools/tabletspec.json. Edit the generator.
//
// MAKING. A lectern's Study op opens poh_tabletmenu (tools/genmenus.py) and hands back a tablet
// index; ~poh_tab_make does the paying. The level, the runes and the experience all come from
// magic_spell_table - the tablet is the spell, stored - and a staff does NOT pay for a rune here,
// because you are not casting. ~staff_runes is deliberately not called.
//
// BREAKING. No Magic level and no experience: the wiki is explicit that a tablet can be broken by
// anyone and pays nothing. What does survive is the quest gate on Ardougne and Watchtower, and every
// check ~magic_teleport makes about WHERE you are - the wilderness ceiling and ~pre_tele_checks - so
// a tablet is not a way out of a place a spell cannot leave.
//
// The five enchant tablets have no Break: an enchant needs something to enchant, so they are used on
// the ring or amulet and arrive through [opheldu]. The jewellery table is the spell row's own
// convertobj list, so a tablet enchants exactly what the spell enchants.
'''

def emit_rs2(spec, rows, ids):
    tabs = spec['tablets']
    idx = {t['key']: n + 1 for n, t in enumerate(tabs)}
    o = RS2_HEAD.split('\n')

    o += ['// =========================================================================== the tables', '']
    o += ['// Which tablet is the nth on a given lectern. A flat switch rather than an enum so that',
          '// "there is no nth" is 0 and not a lookup failure - poh_tab_pick walks until it gets one.',
          '[proc,poh_tab_nth](int $lect, int $i)(int)',
          'switch_int (calc($lect * ^poh_tab_max + $i)) {']
    for l in spec['lecterns']:
        for i, k in enumerate(l['tablets']):
            o.append('    case %d : return(%d);   // %s: %s'
                     % (l['tier'] * MAX + i, idx[k], l['name'], k))
    o += ['    case default : return(0);', '}', '']

    o += ['// =========================================================================== making', '']
    o += ['// The runes a tablet costs, straight off the spell row. NOT ~staff_runes: a staff pays for',
          '// a spell you cast, and binding one into clay is not casting.',
          '[proc,poh_tab_runes](int $tab)(namedobj, int, namedobj, int, namedobj, int)',
          'def_dbrow $d = ~get_spell_data(enum(int, int, poh_tab_spell, $tab));',
          'return(db_getfield($d, magic_spell_table:runesrequired, 0));', '',
          '// Everything the window needs to know to draw a row green or red.',
          '[proc,poh_tab_have](int $tab)(boolean)',
          'if (inv_total(inv, softclay) < 1) {', '    return(false);', '}',
          'def_namedobj $r1;', 'def_int $c1;', 'def_namedobj $r2;', 'def_int $c2;',
          'def_namedobj $r3;', 'def_int $c3;',
          '$r1, $c1, $r2, $c2, $r3, $c3 = ~poh_tab_runes($tab);',
          'if ($r1 ! null & inv_total(inv, $r1) < $c1) {', '    return(false);', '}',
          'if ($r2 ! null & inv_total(inv, $r2) < $c2) {', '    return(false);', '}',
          'if ($r3 ! null & inv_total(inv, $r3) < $c3) {', '    return(false);', '}',
          'return(true);', '',
          '// One tablet. Returns false the moment it cannot make another - no level, no clay, no runes -',
          '// so ~poh_tab_make_n stops at the first refusal instead of printing the same message ten times.',
          '[proc,poh_tab_make](int $tab)(boolean)',
          'def_dbrow $d = ~get_spell_data(enum(int, int, poh_tab_spell, $tab));',
          'if (stat(magic) < db_getfield($d, magic_spell_table:levelrequired, 0)) {',
          '    mes("You need a Magic level of <tostring(db_getfield($d, magic_spell_table:levelrequired, 0))> to make that tablet.");',
          '    return(false);', '}',
          'if (db_getfield($d, magic_spell_table:members, 0) = true & map_members = ^false) {',
          '    mes("You can only make that on a members\' server.");', '    return(false);', '}',
          'if (inv_total(inv, softclay) < 1) {',
          '    mes("You need a piece of soft clay to make a tablet.");', '    return(false);', '}',
          'if (~poh_tab_have($tab) = false) {',
          '    mes("You do not have enough runes to make that tablet.");',
          '    mes("It needs <enum(int, string, poh_tab_need, $tab)>.");', '    return(false);', '}',
          'def_namedobj $r1;', 'def_int $c1;', 'def_namedobj $r2;', 'def_int $c2;',
          'def_namedobj $r3;', 'def_int $c3;',
          '$r1, $c1, $r2, $c2, $r3, $c3 = ~poh_tab_runes($tab);',
          '// The clay goes first. It does not stack, so its slot comes free before the tablet is added -',
          '// and the tablet does stack, so a full inventory can still take one either way.',
          'inv_del(inv, softclay, 1);',
          'if ($r1 ! null) {', '    inv_del(inv, $r1, $c1);', '}',
          'if ($r2 ! null) {', '    inv_del(inv, $r2, $c2);', '}',
          'if ($r3 ! null) {', '    inv_del(inv, $r3, $c3);', '}',
          'inv_add(inv, enum(int, namedobj, poh_tab_obj, $tab), 1);',
          'stat_advance(magic, db_getfield($d, magic_spell_table:experience, 0));',
          'anim(human_cast_enchantring, 0);',
          'spotanim_pl(enchant_ring, 92, 0);',
          'mes("You bind the spell into the clay.");',
          'return(true);', '',
          '// Make 1, 5, 10 or X. The window\'s quantity buttons write %poh_tab_qty and hand it here; the',
          '// loop stops at the first tablet it cannot make, so running out of clay says so once and not',
          '// ten times. Bounded by ^poh_tab_qty_max, an inventory\'s worth: a tablet needs a soft clay and',
          '// clay does not stack, so no more than that can be carried to the lectern anyway.',
          '[proc,poh_tab_make_n](int $tab, int $count)',
          'def_int $i = 0;',
          'while ($i < $count & $i < ^poh_tab_qty_max) {',
          '    $i = calc($i + 1);',
          '    if (~poh_tab_make($tab) = false) {',
          '        return;', '    }',
          '    if ($i < $count) {',
          '        p_delay(2);', '    }',
          '}', '',
          '// The animation OSRS plays when a tablet is broken (seq 4069) and the graphic that goes with',
          '// it (spotanim 678, which animates itself). One proc, so every break path looks the same and',
          '// there is one place to change it.',
          '[proc,poh_tab_breakanim]',
          'anim(%s, 0);' % spec['break']['anim'],
          'spotanim_pl(%s, %d, 0);' % (spec['break']['spot'], spec['break']['height']), '']

    o += ['// =========================================================================== breaking', '']
    o += ['// Every check ~magic_teleport makes about where you are, and none of the ones about what you',
          '// can cast. A tablet is not a way out of the trawler, a duel or deep wilderness.',
          '[proc,poh_tab_teleport](int $spell, obj $tab)',
          'if (~wilderness_level(coord) > 20) {',
          '    mes("A mysterious force blocks your teleport!");',
          '    mes("You can\'t use this teleport after level 20 wilderness.");', '    return;', '}',
          'if (~pre_tele_checks(coord) = false) {', '    return;', '}',
          'if (inv_total(inv, $tab) < 1) {', '    return;', '}',
          'inv_del(inv, $tab, 1);',
          'mes("You break the tablet.");',
          'def_dbrow $d = ~get_spell_data($spell);',
          'def_coord $dest = map_findsquare(db_getfield($d, magic_spell_table:tele_coord, 0), 0, 2, ^map_findsquare_lineofwalk);',
          '// NOT ~player_teleport_normal: that plays human_castteleport, which is the animation for',
          '// CASTING the spell. Breaking a tablet has its own. This is that proc with the pair swapped -',
          '// the sound, the delay and ~p_telejump_safe are exactly its.',
          'if_close;',
          'p_stopaction;',
          'sound_synth(teleport_all, 1, 0);',
          '~poh_tab_breakanim;',
          'p_delay(2);',
          '~p_telejump_safe($dest);', '',
          '// The house tablet does not name a coord - ~poh_enter builds the instance and picks the door.',
          '[proc,poh_tab_gohome](obj $tab)',
          'if (%poh_owned = 0) {',
          '    mes("You don\'t own a house. The estate agent in Rimmington will sell you one.");',
          '    return;', '}',
          'if (%poh_instance ! null) {',
          '    mes("You are already in your house.");', '    return;', '}',
          'if (~wilderness_level(coord) > 20) {',
          '    mes("A mysterious force blocks your teleport!");',
          '    mes("You can\'t use this teleport after level 20 wilderness.");', '    return;', '}',
          'if (~pre_tele_checks(coord) = false) {', '    return;', '}',
          'if (inv_total(inv, $tab) < 1) {', '    return;', '}',
          'inv_del(inv, $tab, 1);',
          'mes("You break the tablet.");',
          'p_stopaction;',
          'sound_synth(teleport_all, 1, 0);',
          '~poh_tab_breakanim;',
          'p_delay(2);',
          'anim(null, 0);',
          '~poh_enter(false);', '',
          '// Bones to bananas and bones to peaches. The product is the spell row\'s own convertobj, so',
          '// this is the same conversion [label,magic_spell_convert_bones] does, minus the runes.',
          '[proc,poh_tab_convert](int $spell, obj $tab)',
          'def_int $total = inv_total(inv, bones);',
          'if ($total < 1) {',
          '    mes("You aren\'t holding any bones!");', '    return;', '}',
          'if (inv_total(inv, $tab) < 1) {', '    return;', '}',
          'def_dbrow $d = ~get_spell_data($spell);',
          'def_namedobj $product;', 'def_seq $anim;', 'def_spotanim $spotanim;', 'def_synth $sound;',
          '$product, $anim, $spotanim, $sound = ~magic_spell_search_convertobj($d, null);',
          'inv_del(inv, $tab, 1);',
          'mes("You break the tablet.");',
          'inv_del(inv, bones, $total);',
          'inv_add(inv, $product, $total);',
          'sound_synth($sound, 0, 0);',
          '~poh_tab_breakanim;',
          'p_delay(2);', '',
          '// An enchant needs a target, so the five enchant tablets arrive here from [opheldu] with the',
          '// jewellery in last_useitem. Same convertobj list the spell uses, so a tablet enchants exactly',
          '// what the spell enchants and says the same thing when it cannot.',
          '[proc,poh_tab_enchant](int $spell, obj $tab)',
          'def_obj $target = last_useitem;',
          'def_int $slot = last_useslot;',
          'if (inv_total(inv, $tab) < 1 | inv_getobj(inv, $slot) ! $target) {', '    return;', '}',
          'def_dbrow $d = ~get_spell_data($spell);',
          'def_namedobj $final;', 'def_seq $anim;', 'def_spotanim $spotanim;', 'def_synth $sound;',
          '$final, $anim, $spotanim, $sound = ~magic_spell_search_convertobj($d, $target);',
          'if ($final = null) {',
          '    ~magic_spell_specificobj_reqmessage($d, $target);',
          '    mes(db_getfield($d, magic_spell_table:additional_reqmessage, 0));', '    return;', '}',
          'if (oc_members($final) = true & map_members = ^false) {',
          '    mes("You can only make that on a members\' server.");', '    return;', '}',
          'inv_del(inv, $tab, 1);',
          'mes("You break the tablet.");',
          'inv_setslot(inv, $slot, $final, 1);',
          '~poh_tab_breakanim;',
          'sound_synth($sound, 0, 0);',
          'mes("You successfully enchant the <lowercase(oc_name($target))>.");',
          'p_delay(1);', '']

    o += ['// =========================================================================== the triggers', '']
    for t in tabs:
        k = t['kind']
        if k == 'enchant':
            o += ['[opheldu,%s]' % t['obj'],
                  '~poh_tab_enchant(^%s, %s);' % (t['spell'], t['obj']), '']
            continue
        o.append('[opheld1,%s]' % t['obj'])
        if 'quest' in t:
            var, done, mesg = t['quest']
            o += ['if (%s < %s) {' % (var, done), '    mes(%s);' % q(mesg), '    return;', '}']
        if k == 'teleport':
            o.append('~poh_tab_teleport(^%s, %s);' % (t['spell'], t['obj']))
        elif k == 'house':
            o.append('~poh_tab_gohome(%s);' % t['obj'])
        elif k == 'convert':
            o.append('~poh_tab_convert(^%s, %s);' % (t['spell'], t['obj']))
        else:
            raise SystemExit('unknown tablet kind %r' % k)
        o.append('')
    write('scripts/skill_construction/scripts/poh_tablets.rs2', o)
    return o

# --------------------------------------------------------------------------- constants

CONST_MARK = '// ---- the lecterns (poh_tablets.rs2) ----'

def emit_constant(spec, path='scripts/skill_construction/configs/construction.constant'):
    """Appended AFTER the block tools/genfurn.py rewrites, so the two generators never touch
    the same lines. Replaced in place on a re-run."""
    src = read(path).split('\n')
    block = [CONST_MARK,
             '// GENERATED by tools/gentablets.py from tools/tabletspec.json.',
             '//',
             '// How many tablets there are, and how many a lectern can list. The second number is also the',
             '// stride of ~poh_tab_nth\'s switch key and the row count of poh_tabletmenu - the biggest OSRS',
             '// lectern lists exactly eight, so today no lectern needs the second page the window can show.',
             '^poh_tab_items = %d' % len(spec['tablets']),
             '^poh_tab_max = %d' % MAX,
             '',
             '// How many tablets one Study can make before the window closes and you click again. An',
             '// inventory\'s worth: the bound exists because a menu loop that cannot end hangs the script,',
             '// not because there is any reason to stop you.',
             '^poh_tab_loops = 28',
             '',
             '// The cap on Make X (the window\'s quantity buttons, tools/genmenus.py). An inventory\'s',
             '// worth: a tablet costs a soft clay and clay does not stack, so more than this cannot be',
             '// carried to the lectern in the first place. The buttons themselves - 1, 5, 10 - are in',
             '// tools/tabletspec.json, written into the window rather than into constants.',
             '^poh_tab_qty_max = %d' % spec['quantities']['max'],
             '']
    if CONST_MARK in src:
        i = src.index(CONST_MARK)
        j = i + 1
        while j < len(src) and not src[j].startswith('// ---- '):
            j += 1
        src[i:j] = block
    else:
        while src and not src[-1].strip():
            src.pop()
        src += ['', ''] + block
    write(path, src, like=path)

# --------------------------------------------------------------------------- the house spell row

def emit_house_spell(spec):
    """A magic_spell_table row for Teleport to house, and its id. Both append-only: if the row
    or the constant is already there the file is left exactly as it is."""
    h = spec['house_spell']
    cid = 'scripts/skill_combat/configs/magic/spells.constant'
    src = read(cid).split(NL)
    if not any(l.startswith('^teleport_to_house ') for l in src):
        while src and not src[-1].strip():
            src.pop()
        src += ['',
                '// Teleport to house (Corey, 2026-09-11). No button and no spellbook entry - the spell was',
                '// added to the game with Construction, after 377 - but its tablet needs a recipe, and every',
                '// other tablet reads its recipe out of magic_spell_table. So the row exists and only',
                '// poh_tablets.rs2 asks for this id.',
                '^teleport_to_house = %d' % h['id']]
        write(cid, src, like=cid)

    dp = 'scripts/skill_magic/configs/magic_spells.dbrow'
    src = read(dp).split(NL)
    if any(l.strip() == '[magic_spell_teleport_to_house]' for l in src):
        return
    runes = [x for pair in h['runes'] for x in (pair[0], str(pair[1]))]
    runes += ['null', 'null'] * (3 - len(h['runes']))
    while src and not src[-1].strip():
        src.pop()
    src += ['',
            "// Teleport to House. See tools/tabletspec.json: nothing casts this - there is no button for it",
            "// at 377 - the row is here so the house tablet's recipe lives with every other tablet's, and is",
            "// reached only by ~get_spell_data(^teleport_to_house) in poh_tablets.rs2.",
            '[magic_spell_teleport_to_house]',
            'table=magic_spell_table',
            'data=spell,^teleport_to_house',
            'data=members,true',
            'data=name,"Teleport to House"',
            'data=levelrequired,%d' % h['levelrequired'],
            'data=runesrequired,%s' % ','.join(runes),
            'data=experience,%d' % h['experience']]
    write(dp, src, like=dp)


# --------------------------------------------------------------------------- main

if __name__ == '__main__':
    spec = json.load(open(SPEC))
    emit_house_spell(spec)
    emit_constant(spec)
    rows = spell_rows()
    ids = spell_ids()
    for t in spec['tablets']:
        if t['spell'] not in rows:
            raise SystemExit('no magic_spell_table row for ^%s' % t['spell'])
        if t['spell'] not in ids:
            raise SystemExit('no ^%s in spells.constant' % t['spell'])

    p12, p11 = widths()
    for t in spec['tablets']:
        lab = t.get('label', t['name'])
        if 'label' in t and not t['name'].startswith(lab.rstrip('.')):
            raise SystemExit('window label %r is not a trim of the obj name %r' % (lab, t['name']))
        n = p12.width(lab)
        if n > NAME_PX:
            raise SystemExit('tablet label %r is %dpx, column is %d' % (lab, n, NAME_PX))
        s = need_text(spec, rows[t['spell']]['runes'])
        w = p11.width(s)
        if w > NEED_PX:
            raise SystemExit('needs line %r is %dpx, column is %d' % (s, w, NEED_PX))

    packids = emit_objpack(spec)
    emit_objs(spec, rows, obj_costs(), packids)
    emit_enum(spec, rows, packids)
    emit_rs2(spec, rows, packids)
    print('%d tablets, obj ids %d..%d' % (len(spec['tablets']),
                                          min(packids.values()), max(packids.values())))
    for l in spec['lecterns']:
        print('  %-24s %d tablets' % (l['name'], len(l['tablets'])))
