#!/usr/bin/env python3
"""Write the triggers for the four adopted cache windows.

WHY GENERATED. A window of N products times four count buttons is 4N near-identical [if_button]
blocks - 32 for the smelt window, 32 for the tanner, 21 for silver casting. Typed by hand, the one
that matters is the one that gets the wrong argument, and it looks exactly like its 31 neighbours.
So the repetition is generated from tools/adoptspec.json and the logic is hand-written procs this
calls into.

WHAT IS NOT HERE. No level, cost, message or experience figure is written by this tool for
smelting or tanning - smelting reads the smelting_struct the bar obj already carries, and tanning
reads the ^tanner_*_cost constants that tanner.constant already holds. The churn's figures are in
the spec because the churn did not exist; every one of them is off that product's own wiki page
and the three pages agree with each other.

THE COLUMN ORDER IS THE PANEL'S, NOT THE CONFIG'S. genadopt named the smelt buttons from their own
option text, so smelt_1_silver is the third column because the panel says Silver third. The
smelting.struct file lists the bars bronze, iron, STEEL, SILVER - the other way round. This tool
joins on the button name, so the two orders cannot be confused.

    python3 tools/genwindows.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, 'tools/adoptspec.json')
NL = '\n'

# What each window's buttons actually offer. These are not the same: the furnace says
# Smelt 1/5/10/X and the tanner says Tan All/X/5/1, and an earlier version of this tool assumed
# both were 1/5/10/X and generated eight triggers for a tan_10_<n> that does not exist. The panel
# is the authority - genadopt named the components from the panel's own option text, so a count
# that is not on the panel produces a trigger naming a component that is not there, which is what
# windows_battery group 7 asks about.
SMELT_COUNTS = [('1', '1'), ('5', '5'), ('10', '10'), ('x', None)]        # None = ask
TAN_COUNTS = [('all', '^max_32bit_int'), ('x', None), ('5', '5'), ('1', '1')]


def write(rel, head, body):
    p = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    text = NL.join(['// %s' % l for l in head] + [''] + body).rstrip(NL) + NL
    open(p, 'w', encoding='utf-8', newline='').write(text)
    return p, text.count('[')


def button(iface, com, call):
    """Every [if_button] body is wrapped in p_finduid.

    An [if_button] trigger is handed active_player and NOT p_active_player - claude/
    rs2-player-pointer-contexts.md says so, and the XP-lock round paid for not reading it with 22
    identical build errors. Everything these buttons do (if_close, p_countdialog, a queue, a varp
    write) needs the player pointer, so the guard is not optional and is not decoration."""
    return ['[if_button,%s:%s]' % (iface, com),
            'if (p_finduid(uid) = true) {',
            '    %s' % call,
            '}',
            '']


def smelt(panel):
    bars = panel['content']['bars']
    head = [
        "The furnace's Smelt window.",
        '',
        'GENERATED by tools/genwindows.py. Edit tools/adoptspec.json, not this file.',
        '',
        'THE FURNACE HAS SAID "Smelt" SINCE THE FORK BEGAN. Seven locs in the 377 cache carry',
        'op2=Smelt and nothing answered oploc2 on any of them, so right-clicking a furnace offered',
        'the option and clicking it did nothing - no error, no log line. Same shape as Lvl-6',
        'Enchant and the four unwired spellbook buttons: the cache is ahead of the content and the',
        'symptom is silence.',
        '',
        'Nothing here knows a level, an ore or an experience figure. ~smelt_bar in smelting.rs2 is',
        'the one place a bar is smelted, and it reads the bar obj\'s own smelting_struct, which is',
        'what using an ore on the furnace has always read.',
    ]
    b = ['[oploc2,_smithing_furnace]', '~smelt_window_open;', '']
    b += ['// The eight icons ship as obj_bronze_bar in the cache, so the server sets each one.',
          '// if_setobject copies xan/yan/zoom off the ObjType, so there is no zoom table here.',
          '[proc,smelt_window_open]']
    for i, bar in enumerate(bars, 1):
        b.append('if_setobject(smelt_window:icon%d, %s, ^smelt_window_scale);' % (i, bar['obj']))
    b += ['if_openmain(smelt_window);', '']
    for bar in bars:
        for suffix, count in SMELT_COUNTS:
            com = 'smelt_%s_%s' % (suffix, bar['column'])
            call = ('@smelt_window_go(%s, %s);' % (bar['obj'], count) if count
                    else '@smelt_window_ask(%s);' % bar['obj'])
            b += button('smelt_window', com, call)
    b += [
        '// Smelt X. p_countdialog parks the script on the amount prompt and comes back in',
        '// last_int, the way cooking.rs2 already does it.',
        '[label,smelt_window_ask](namedobj $bar)',
        'p_countdialog;',
        '@smelt_window_go($bar, last_int);',
        '',
        '[label,smelt_window_go](namedobj $bar, int $count)',
        'if ($count < 1) {',
        '    return;',
        '}',
        'if_close;',
        'weakqueue*(smelt_window_run, 0)($bar, $count);',
        '',
        '// One bar per pass, re-queueing itself - the cook_generic shape. ~smelt_bar does the',
        '// checks, so a run that outlives the ore or the coal stops with the struct\'s own message.',
        '[queue,smelt_window_run](namedobj $bar, int $count)',
        'if ($count < 1) {',
        '    return;',
        '}',
        'def_struct $struct = oc_param($bar, smelting_struct);',
        'if (stat(smithing) < struct_param($struct, levelrequired)) {',
        '    ~mesbox(struct_param($struct, levelfailure));',
        '    return;',
        '}',
        'if (inv_total(inv, struct_param($struct, ingredient)) < struct_param($struct, bar_count)) {',
        '    ~mesbox(struct_param($struct, processfailure));',
        '    return;',
        '}',
        'if (struct_param($struct, ingredient_secondary) ! null',
        '        & inv_total(inv, struct_param($struct, ingredient_secondary)) < struct_param($struct, ingredient_secondary_count)) {',
        '    ~mesbox(struct_param($struct, processfailure));',
        '    return;',
        '}',
        'weakqueue*(smelt_window_run, 4)($bar, sub($count, 1));',
        '~smelt_bar($struct, $bar);',
    ]
    return write('scripts/skill_smithing/scripts/smelting/smelt_window.rs2', head, b)


def tan(panel):
    rows = panel['content']['rows']
    cells = panel['content']['cells']
    head = [
        "The tanner's window.",
        '',
        'GENERATED by tools/genwindows.py. Edit tools/adoptspec.json, not this file.',
        '',
        "ELLIS HAS ADVERTISED Trade SINCE THE FORK BEGAN and nothing answered opnpc3 on him. The",
        'Canifis tanner\'s Trade option does work - it jumps straight to the chat cascade - so the',
        'two tanners have disagreed about whether their own right-click menu does anything.',
        '',
        'The panel is generic: eight cells, each with a placeholder "Hide" and "Cost" label the',
        'server overwrites. Six hides are tannable in this build; the two snake hides have no obj',
        'in pack/obj.pack, so their cells are hidden rather than drawn dead.',
        '',
        'The costs come from tanner.constant, and WHICH SET depends on the npc - Canifis charges',
        '2/5/45 against Al Kharid\'s 1/3/20 - so the Cost line is filled per tanner, not per hide.',
        'Overwriting a LABEL and never a number: neither of those two texts carries a %1.',
    ]
    # Only Ellis. sbott.rs2 already declares [opnpc3,werewolftanner] and a duplicate trigger is a
    # hard build error - rs2check rule 2 caught this on the first run. That one now calls the same
    # proc, so both tanners open the same window.
    b = ['[opnpc3,ellis_tanner]', '~tan_window_open;', '']
    b += ["// ASK WHICH TANNER HERE, NOT IN A BUTTON. npc_type needs the active_npc pointer. An",
          "// [opnpc3,...] trigger has it; an [if_button,...] trigger does not, and the build says",
          "// so on all 32 buttons at once. So the question is asked once, while the npc is still",
          "// in scope, and the answer lives in %tan_window_canifis until the window closes.",
          '[proc,tan_window_open]',
          'def_int $cost;',
          '%tan_window_canifis = false;',
          'if (npc_type = werewolftanner) {',
          '    %tan_window_canifis = true;',
          '}']
    for i, r in enumerate(rows, 1):
        b += ['if_sethide(tan_window:cell%d, false);' % i,
              'if_setobject(tan_window:hide%d, %s, ^tan_window_scale);' % (i, r['hide']),
              'if_settext(tan_window:name%d, "%s");' % (i, r['label']),
              '$cost = ~tan_window_cost(^%s, ^%s);' % (r['alkharid'], r['canifis']),
              '// ~pluralise so a soft leather reads "1 coin" and not "1 coins".',
              'if_settext(tan_window:cost%d, "<~pluralise($cost, \"coin\")>");' % i]
    for i in range(len(rows) + 1, cells + 1):
        b += ['// no obj in this build for the snake hides - the cell is hidden, not left dead',
              'if_sethide(tan_window:cell%d, true);' % i]
    b += ['if_openmain(tan_window);', '']
    b += ["// Which tanner's prices. Canifis is not a markup on Al Kharid - it is 2/5/45 against",
          '// 1/3/20 - so both constants are read and the tanner that opened the window picks.',
          '// This reads the varp and NOT npc_type, because the buttons reach it with no npc.',
          '[proc,tan_window_cost](int $al_kharid, int $canifis)(int)',
          'if (%tan_window_canifis = true) {',
          '    return($canifis);',
          '}',
          'return($al_kharid);',
          '']
    for i, r in enumerate(rows, 1):
        for suffix, count in TAN_COUNTS:
            com = 'tan_%s_%d' % (suffix, i)
            args = '%s, %s, ^%s, ^%s' % (r['hide'], r['leather'], r['alkharid'], r['canifis'])
            call = ('@tan_window_go(%s, %s);' % (args, count) if count
                    else '@tan_window_ask(%s);' % args)
            b += button('tan_window', com, call)
    for i in range(len(rows) + 1, cells + 1):
        for suffix, _ in TAN_COUNTS:
            b += button('tan_window', 'tan_%s_%d' % (suffix, i), '@tan_window_dead;')
    b += [
        '// The two hidden cells still carry buttons, and a component with no trigger that',
        '// something names is a build error. They answer, and say nothing a player can reach.',
        '[label,tan_window_dead]',
        '~displaymessage(^dm_default);',
        '',
        '[label,tan_window_ask](namedobj $hide, namedobj $leather, int $al_kharid, int $canifis)',
        'p_countdialog;',
        '@tan_window_go($hide, $leather, $al_kharid, $canifis, last_int);',
        '',
        '[label,tan_window_go](namedobj $hide, namedobj $leather, int $al_kharid, int $canifis, int $count)',
        'if ($count < 1) {',
        '    return;',
        '}',
        'def_int $price = ~tan_window_cost($al_kharid, $canifis);',
        'def_int $have = inv_total(inv, $hide);',
        'if ($have < 1) {',
        '    mes("You don\'t have any <lowercase(oc_name($hide))> to tan.");',
        '    return;',
        '}',
        'def_int $afford = divide(inv_total(inv, coins), $price);',
        'if ($afford < 1) {',
        '    mes("You haven\'t got enough coins to pay for that.");',
        '    return;',
        '}',
        'def_int $doing = min(min($count, $have), $afford);',
        'inv_del(inv, $hide, $doing);',
        'inv_del(inv, coins, multiply($doing, $price));',
        'inv_add(inv, $leather, $doing);',
        'if ($doing = 1) {',
        '    mes("The tanner tans your <lowercase(oc_name($hide))>.");',
        '} else {',
        '    mes("The tanner tans <tostring($doing)> <lowercase(oc_name($hide))>s for you.");',
        '}',
        'if (inv_total(inv, coins) < $price & inv_total(inv, $hide) > 0) {',
        '    mes("You haven\'t got enough coins to pay for more.");',
        '}',
    ]
    return write('scripts/skill_crafting/scripts/leather/tan_window.rs2', head, b)


def silver(panel):
    prods = panel['products']
    head = [
        'The furnace\'s Silver Casting window.',
        '',
        'GENERATED by tools/genwindows.py. Edit tools/adoptspec.json, not this file.',
        '',
        'WHAT THIS REPLACES. [label,craft_silver] in jewellery.rs2 is a seven-branch cascade of',
        'p_choice2 and p_choice3 combinations, one per subset of the three moulds it knows about,',
        'and it covers three of the panel\'s seven products. The panel does the same job with two',
        'layers per product - one holding the item, one saying which mould you are missing - and',
        'if_sethide picking between them. if_sethide only works on layers, and these are layers.',
        '',
        'THIS IS THE ONE PLACE "keep both paths" COULD NOT HOLD. The old cascade and the window',
        'are the same click - a silver bar on a furnace - so one of them has to win, and the',
        'window is the one that shows all seven products and names the mould you lack.',
        '',
        'Three of the seven have no obj in pack/obj.pack at all: the lightning rod, the silvthrill',
        'rod and the demonic sigil belong to quests this build does not have. Their moulds do not',
        'exist either, so those three panels simply never flip to the make state. Nothing special',
        'is done about them and nothing needs to be.',
    ]
    b = ['// There is NO [oplocu,_smithing_furnace] here on purpose: smelting.rs2 already owns that',
         '// trigger and a duplicate is a hard build error. Its silver_bar case calls this proc.',
         '[proc,silver_casting_open]']
    for p in prods:
        if p['struct']:
            b += ['if (inv_total(inv, %s) > 0) {' % p['mould'],
                  '    inv_transmit(%s, silver_casting:slot_%s);' % (p['inv'], p['key']),
                  '    if_sethide(silver_casting:make_%s, false);' % p['key'],
                  '    if_sethide(silver_casting:need_%s, true);' % p['key'],
                  '} else {',
                  '    if_sethide(silver_casting:make_%s, true);' % p['key'],
                  '    if_sethide(silver_casting:need_%s, false);' % p['key'],
                  '}']
        else:
            b += ['// %s: a quest step with no Crafting level or experience to copy, and nothing' % p['key'],
                  '// in this build hands out its mould, so it stays on the need side by itself.',
                  'if_sethide(silver_casting:make_%s, true);' % p['key'],
                  'if_sethide(silver_casting:need_%s, false);' % p['key']]
    b += ['if_openmain(silver_casting);', '']
    for p in prods:
        if not p['struct']:
            continue
        for n, count in ((1, 1), (2, 5), (3, 10)):
            b += ['[inv_button%d,silver_casting:slot_%s]' % (n, p['key']),
                  'if (p_finduid(uid) = true) {',
                  '    @silver_casting_go(%s, %s, %d);' % (p['obj'], p['mould'], count),
                  '}',
                  '']
    b += [
        '[label,silver_casting_go](namedobj $product, namedobj $mould, int $count)',
        'if (inv_total(inv, $mould) < 1) {',
        '    ~mesbox("You require a mould to make that.");',
        '    return;',
        '}',
        'if_close;',
        'weakqueue*(silver_casting_run, 0)($product, $count);',
        '',
        '// The level, the experience and the name all come off crafting_jewelry_struct, which is',
        '// the same struct [label,craft_silver] read. The tiara had no struct until this round,',
        '// because nothing had ever offered to make one.',
        '[queue,silver_casting_run](namedobj $product, int $count)',
        'if ($count < 1) {',
        '    return;',
        '}',
        'if (inv_total(inv, silver_bar) < 1) {',
        '    mes("You need a silver bar to make that.");',
        '    return;',
        '}',
        'def_struct $struct = oc_param($product, crafting_jewelry_struct);',
        'def_int $level = struct_param($struct, levelrequired);',
        'if (stat(crafting) < $level) {',
        '    ~mesbox("You need at least level <tostring($level)> Crafting to make that.");',
        '    return;',
        '}',
        'weakqueue*(silver_casting_run, 3)($product, sub($count, 1));',
        'anim(human_furnace, 0);',
        'sound_synth(furnace, 1, 0);',
        'inv_del(inv, silver_bar, 1);',
        'inv_add(inv, $product, 1);',
        'stat_advance(crafting, struct_param($struct, productexp));',
        '// Confirmed, no period at the end. https://i.imgur.com/sCKRVO9.png',
        'mes("You make <~add_article(struct_param($struct, name))>");',
    ]
    return write('scripts/skill_crafting/scripts/jewellery/silver_casting.rs2', head, b)


def churn(spec):
    c = [p for p in spec['panels'] if p['iface'] == 'churn_milk'][0]['content']
    prods = {p['key']: p for p in c['products']}
    head = [
        'The dairy churn.',
        '',
        'GENERATED by tools/genwindows.py. Edit tools/adoptspec.json, not this file.',
        '',
        'TWO Dairy churn LOCS IN THE CACHE CARRY op1=Churn and nothing answered either of them.',
        'Unlike the other three windows in this round, there was no slower path behind it: the',
        'churn has never worked at all.',
        '',
        'THE THREE PANELS ARE THE THREE INPUTS. Milk makes all three products, cream makes butter',
        'and cheese, butter makes cheese - and the cache has exactly three churn windows, with',
        'three, two and one button. That is not a coincidence to be verified later; it is the',
        'thing that says which window belongs to which input.',
        '',
        'The level is the product\'s whatever it was churned from; the experience is the pair\'s.',
        'Every figure is from that product\'s own OSRS wiki page and the three pages agree.',
    ]
    b = []
    for loc in c['locs']:
        b += ['[oploc1,%s]' % loc, '~churn_open;', '']
    b += [
        '// Which window to open is decided by what you are carrying, richest input first, because',
        '// milk can become anything and butter can only become cheese.',
        '[proc,churn_open]',
        'if (inv_total(inv, bucket_milk) > 0) {',
        '    if_openmain(churn_milk);',
        '    return;',
        '}',
        'if (inv_total(inv, pot_of_cream) > 0) {',
        '    if_openmain(churn_cream);',
        '    return;',
        '}',
        'if (inv_total(inv, pot_of_butter) > 0) {',
        '    if_openmain(churn_butter);',
        '    return;',
        '}',
        'mes("You have nothing to churn.");',
        '',
    ]
    for iface, src in c['inputs'].items():
        for p in c['products']:
            if src not in p['from']:
                continue
            b += button(iface, 'churn_%s' % p['key'],
                        '@churn_go(%s, %s, %d, %d);'
                        % (src, p['obj'], p['level'], p['from'][src]))
    b += [
        '[label,churn_go](namedobj $from, namedobj $to, int $level, int $xp)',
        'if (stat(cooking) < $level) {',
        '    ~mesbox("You need a Cooking level of <tostring($level)> to make <lowercase(oc_name($to))>.");',
        '    return;',
        '}',
        'if_close;',
        'weakqueue*(churn_run, 0)($from, $to, $xp, inv_total(inv, $from));',
        '',
        '// Churns the lot, the way the panel offers no count to choose.',
        '[queue,churn_run](namedobj $from, namedobj $to, int $xp, int $count)',
        'if ($count < 1) {',
        '    return;',
        '}',
        'if (inv_total(inv, $from) < 1) {',
        '    return;',
        '}',
        'weakqueue*(churn_run, 3)($from, $to, $xp, sub($count, 1));',
        'inv_del(inv, $from, 1);',
        'inv_add(inv, $to, 1);',
        'stat_advance(cooking, $xp);',
        'mes("You churn the <lowercase(oc_name($from))> into <lowercase(oc_name($to))>.");',
    ]
    return write('scripts/skill_cooking/scripts/churn/churn.rs2', head, b)


def main():
    spec = json.load(open(SPEC, encoding='utf-8'))
    by = {p['iface']: p for p in spec['panels']}
    for path, n in (smelt(by['smelt_window']), tan(by['tan_window']),
                    silver(by['silver_casting']), churn(spec)):
        print('%-62s %3d blocks' % (os.path.relpath(path, ROOT), n))


main()
